"""Course document comparisons, plus explicitly requested business-plan clarification."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[3]/'dist/cis464-content.json'
d=json.loads(p.read_text())
overview='Business case = WHY this project is worth doing.\nProject charter = official approval and authority to begin.\nProject management plan = HOW this project will be carried out and managed.\nBusiness plan = how a BUSINESS will operate and grow; this is not another name for a project management plan.\nStakeholder register = WHO is involved or affected and what we know about them.\nStakeholder engagement plan = HOW we will involve and work with those people.\nBaseline = an approved reference used to compare planned and actual performance.'
scope='Your Chapter 3 slides name the project documents above. Business plan is an extra terminology clarification requested by you, not a separately identified exam requirement in these slides.'
for n in [42,43,44]:
 q=next(q for q in d['questions'] if q['number']==n)
 q['answer']+='\n\nCompare the names:\n'+overview+'\n\n'+scope
rows=[
(42,'A university is deciding whether replacing its registration system is worth the cost. Which document compares the problem, options, benefits, costs, and risks?','Business case',['Project charter','Project management plan','Stakeholder register'],'Remember: the decision here is WHY the investment makes sense. The business case justifies it. A charter provides formal authorization; the management plan explains how approved work will be managed.','The case compares keeping the old system with replacing it, estimates the costs and benefits, and recommends an option.'),
(43,'The university has accepted the justification. Which document formally authorizes the project and establishes the manager’s authority?','Project charter',['Business case','Project management plan','Stakeholder engagement plan'],'Remember: convincing people that work is worthwhile is different from officially approving it. The charter is the authorization document; the business case is the justification.','An authorized sponsor signs the charter for the registration-system project so the manager can apply resources under the organization’s rules.'),
(44,'The project is approved. Which document guides how it will be executed, monitored, controlled, and closed?','Project management plan',['Business case','Project charter','Business plan'],'Remember: this question asks HOW one project will be managed. The plan coordinates the work and management approach; it is broader than just a calendar of dates.','The team’s management plan explains its approach to scope, schedule, costs, risks, changes, and delivery of the registration system.'),
(42,'Which distinction between a business case and a business plan is correct?','A business case justifies a proposed investment; a business plan describes how a business will operate and grow',['A business case formally authorizes a project; a business plan is its stakeholder list','A business case and business plan are interchangeable names for the same document','A business case is the daily task schedule; a business plan records only project approvals'],'Remember: a CASE argues for a particular investment or decision. A business PLAN describes the business itself. Both can discuss money, but their purpose and scope differ. '+scope,'A café’s business plan describes its customers, operations, and finances. A business case evaluates whether that café should invest in a new ordering system.'),
(44,'Are a business plan and a project management plan the same thing?','No: one guides a business; the other guides management of a particular project',['Yes: both names mean the document that authorizes a project','No: a business plan lists stakeholders; a project management plan only names the sponsor','Yes: both names mean only the approved project budget'],'Remember: identify what is being planned. An ongoing business and a temporary project are different things. '+scope,'The café’s business plan concerns running the café. The project management plan concerns organizing the temporary work to install its new ordering system.'),
(46,'You need a structured record of stakeholders and their interests, influence, and relevant details. Which document should you use?','Stakeholder register',['Stakeholder engagement plan','Project charter','Business case'],'Remember: a REGISTER records WHO the stakeholders are and what you know about them. An engagement plan uses that information to decide how to work with them.','The register records students, advisers, and support staff, including their concerns and influence over the registration-system project.'),
(47,'You already know who the stakeholders are. Which document sets strategies for involving them and addressing their communication needs?','Stakeholder engagement plan',['Stakeholder register','Business case','Project charter'],'Remember: the register identifies and assesses people; the engagement plan turns that knowledge into an approach for involving them. Engagement means meaningful participation and interaction.','Because advisers are worried about the new workflow, the plan includes demonstrations, feedback sessions, and updates suited to their needs.'),
(41,'Which distinction between a project management plan and a baseline is correct?','The plan guides project management; a baseline is an approved reference for measuring performance',['The plan is only a list of stakeholders; the baseline authorizes the project','Both are forecasts that can be overwritten whenever actual results differ','The baseline explains the whole business strategy; the plan only justifies funding'],'Remember: a baseline is a comparison point, not merely the latest prediction. The management plan incorporates approved baselines along with how the work is managed. Changes to baselines follow appropriate approval procedures.','The approved schedule says testing should finish Friday. A forecast now says Monday. Comparing them reveals a delay; rewriting the baseline just to hide it would erase the useful comparison.')
]
for i,(n,q,correct,wrong,teach,example) in enumerate(rows,1):
 d['checks'].append(dict(id=f'464-doc-{i}',source=n,section=3,q=q,correct=correct,answer=correct,distractors=wrong,teach=teach,example=example,mainPractice=True))
d['references'].append(dict(title='SBA · Business plans (requested terminology clarification)',url='https://www.sba.gov/counseling/plan-your-business/',questions=[42,44]))
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
