"""Individual checks for named concepts in the supplied chapter material."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
p=ROOT/'dist/cis464-content.json'
d=json.loads(p.read_text())
# source lesson, term, definition, three plausible alternatives, explanation, example
rows=[
(59,'Simple reflex agent','An agent that follows condition–action rules using the current observation','An agent that remembers hidden environmental state|An agent that compares outcomes using a utility score|An agent defined by improving its rules from experience','Remember: IF a condition is true, THEN take its assigned action. Current input triggers the rule; learning from experience is not required.','A thermostat switches the heater on when the current temperature is below a fixed threshold.'),
(60,'Model-based reflex agent','An agent that uses an internal model and remembered state to interpret current observations','An agent that uses only the current input with no remembered state|An agent defined only by generating text|An agent that must always retrain itself after each action','Remember: it keeps a picture of what may be happening even when it cannot see everything right now. Having a model does not automatically mean it learns.','A robot remembers a wall behind it even when its current sensor is pointed forward.'),
(61,'Goal-based agent','An agent that selects actions by considering whether they help reach a desired outcome','An agent that only reacts to current input using fixed rules|An agent that must rank outcomes by a numeric preference score|An agent that stores observations but never considers future results','Remember: a goal describes the result it is trying to reach. The agent considers possible actions or paths that could get it there.','A route planner searches for a sequence of roads that will reach the requested destination.'),
(62,'Utility-based agent','An agent that compares possible outcomes using a measure of how desirable they are','An agent that treats every goal-reaching outcome as equally desirable|An agent that reacts without comparing alternatives|An agent defined only by storing its previous observations','Remember: several choices may reach the goal, but some fit your preferences better. Utility means how desirable an outcome is according to the chosen measure.','Two routes reach campus. The agent weighs travel time, tolls, and fuel to choose the preferred route.'),
(63,'Learning agent','An agent that changes its behavior using experience or feedback','An agent whose rules must remain unchanged after feedback|An agent defined only by remembering an unseen object|An agent that must choose the shortest route regardless of feedback','Remember: feedback changes how it acts next time. Learning can be combined with goals, an internal model, or utility; these categories can overlap.','After repeated corrections, a ticket-routing agent improves which department it chooses for new tickets.'),
(13,'Forming','The team-development stage when members get oriented and explore roles','The stage when members end their work together|The stage when an established team works effectively|The stage defined by disagreements over roles','Remember: people are just becoming a team. They may be polite and uncertain while trying to understand the purpose and expectations.','New group members introduce themselves and ask what the assignment requires.'),
(13,'Performing','The team-development stage when members work effectively toward shared goals','The stage when members first get acquainted|The stage when the team separates after finishing|The stage when unresolved role conflict first surfaces','Remember: the team can coordinate its effort and solve work problems together. This describes how people work, not a guarantee that every project result is successful.','Members know their responsibilities and help each other resolve obstacles while building the deliverable.'),
(13,'Adjourning','The team-development stage when work ends and the team closes or separates','The stage of first introductions|The stage of establishing working norms|The stage of sustained coordinated performance','Remember: temporary teams eventually finish. People review the experience, hand off results, and move to other work.','After submitting the project, classmates review lessons learned and end their project group.'),
(15,'Initiating','Management activity that establishes and authorizes a project or phase','Doing the planned work to create deliverables|Comparing actual performance with the plan|Completing the formal ending and handoff','Remember: this establishes why the effort should exist and who authorizes it. It is different from carrying out the detailed work.','A sponsor approves a charter for a new registration-system project.'),
(15,'Planning','Management activity that works out objectives and how to achieve them','Only formally authorizing the project|Only performing the approved tasks|Only closing completed contracts','Remember: planning connects the desired result to scope, tasks, timing, resources, risks, and other decisions. Plans can be refined as knowledge improves.','A team identifies the tasks, dependencies, budget, and testing needed before a campus app can launch.'),
(15,'Executing','Management activity that carries out planned work to create results','Only selecting which projects to fund|Only comparing planned and actual progress|Only archiving a completed project','Remember: executing means doing and coordinating the work. It does not mean that monitoring or planning has stopped.','Developers build the agreed features while the manager coordinates the team and resources.'),
(15,'Monitoring and controlling','Tracking performance and taking appropriate action when changes or differences require it','Doing all work without checking its results|Creating a charter as the only management action|Closing a project immediately whenever a task is late','Remember: monitoring asks how things are going; controlling decides what adjustment or approved change is needed.','The manager notices testing is behind schedule, investigates why, and evaluates a recovery plan.'),
(15,'Closing','Management activity that completes a project or phase and arranges its ending','Starting an effort without authorization|Continuously adding new scope|Measuring progress without finishing the effort','Remember: finishing includes acceptance, handoff, records, and lessons as appropriate. Ending the project does not necessarily end use of its product.','The customer accepts the system, support staff receive it, and the project team records lessons learned.'),
(16,'Risk','An uncertain event or condition that could affect objectives','A difference already measured between planned and actual cost|An approved reference plan|A guaranteed requirement that must be included','Remember: uncertain means it may or may not happen. Risks can involve threats or opportunities; an event that has already happened needs handling as a current issue.','A supplier might deliver equipment late, which could delay testing. The team plans a response before it happens.'),
(16,'Resources','People, equipment, materials, or other assets needed to do the work','Only the features promised to the customer|Only the order of tasks on the calendar|Only the authority to approve changes','Remember: resources are what you need to perform work. Money helps obtain resources, but resources also include people and equipment.','Testing requires a tester, test devices, and access to a suitable environment.'),
(16,'Finance','Managing the money side of a project, including costs and funding','Managing only stakeholder communication|Managing only the order of technical tasks|Managing only the product feature list','Remember: funding is money made available; cost is what the work uses or requires. Financial decisions check whether the work can be paid for and is worthwhile.','A manager checks the available budget before approving additional equipment.'),
(18,'Hybrid approach','An approach combining predictive and adaptive practices as appropriate','An approach that forbids all changes after the start|An approach that eliminates all planning|An approach that means every team must use Scrum','Remember: hybrid means combining approaches for a reason. Different parts of the same project can need different levels of upfront definition and adaptation.','The team plans a fixed hardware installation while improving the app interface through short feedback cycles.'),
(24,'Structural frame','A view of an organization emphasizing roles, rules, and formal reporting','A view emphasizing symbols and shared meaning|A view emphasizing competing interests and power|A view emphasizing people’s needs and fit','Remember: structure is the official arrangement of work and authority. An organization chart helps show who reports to whom.','To learn who formally approves a purchase, you examine the reporting structure and purchasing rules.'),
(24,'Human resources frame','A view emphasizing people’s needs, skills, and fit with the organization','A view focused on rituals and symbols|A view focused on formal reporting alone|A view focused on competition for power alone','Remember: this frame asks how the organization and its people can work well together. It is broader than merely the HR department.','A manager considers whether employees have the training and support needed for a new system.'),
(24,'Political frame','A view emphasizing power, interests, negotiation, and competition for resources','A view focused only on official reporting lines|A view focused only on shared ceremonies|A view focused only on individual training needs','Remember: political here means different groups have different interests and influence. It does not necessarily mean party politics or dishonest behavior.','Two departments want the same limited budget, so leaders negotiate priorities.'),
(24,'Symbolic frame','A view emphasizing culture, shared meanings, stories, and rituals','A view focused only on reporting lines|A view focused only on budget competition|A view focused only on staffing skill gaps','Remember: symbols and stories influence what people believe matters. A practice can carry meaning beyond its literal action.','A company’s celebration of customer-service successes signals that helping customers is valued.'),
(25,'Functional organization','An organization grouped by specialties such as finance, marketing, and IT','An organization primarily arranged around dedicated project teams|An organization where project and functional authority are combined|An organization with no continuing specialty departments','Remember: functional means grouped by kind of work. Projects may need coordination across those department boundaries.','A developer reports to the IT department manager while contributing technical work to a business project.'),
(25,'Matrix organization','An organization combining functional and project authority','An organization arranged only around functional departments|An organization arranged only around dedicated projects|An organization in which nobody has formal authority','Remember: the two directions of authority must be coordinated. The balance varies between weak, balanced, and strong matrices.','An analyst receives specialty guidance from a functional manager and project priorities from a project manager.'),
(25,'Projectized organization','An organization structured primarily around projects and their teams','An organization structured only by ongoing specialties|An organization defined by two balanced reporting directions|An organization that handles only ongoing operations','Remember: projects are a main organizing unit, and project managers usually have substantial authority over their teams.','A consulting firm assembles a dedicated team around a client project and its project manager.'),
(20,'Developers in Scrum','The Scrum Team members who create the usable Increment','The single accountability for maximizing product value|The accountability for establishing Scrum and helping team effectiveness|A separate board that authorizes all project changes','Remember: Developers is a Scrum accountability, not a requirement that everyone write software code. The skills needed depend on the product.','Designers, testers, and programmers collaborate to produce a usable improvement during a Sprint.'),
(20,'Sprint Planning','The Scrum event for deciding why the Sprint is valuable, what can be done, and how to approach it','The event for inspecting the completed outcome with stakeholders|The event for improving how the team works after reflection|The daily event for inspecting progress toward the Sprint Goal','Remember: planning connects a short-term goal to selected work and a plan. The team does not simply accept an unlimited task list.','The team selects work that supports a Sprint Goal and discusses how it can deliver it.'),
(20,'Daily Scrum','A short event for Developers to inspect progress toward the Sprint Goal and adapt their plan','A meeting whose main purpose is to present the finished product to customers|A meeting whose main purpose is to authorize the entire project|A meeting whose main purpose is to evaluate company portfolios','Remember: this is for coordinating progress toward the goal. It is not primarily a status report to a boss.','Developers notice a blocked test and adjust today’s work to keep the Sprint Goal achievable.'),
(20,'Sprint Review','An event to inspect the Sprint outcome with stakeholders and consider what to do next','An event focused mainly on improving the team’s working process|An event that starts the Sprint by selecting its goal and work|A daily event focused on the Developers’ immediate plan','Remember: the Review looks at the product and what was learned with stakeholders. The Retrospective focuses on improving how the team works.','Users try the new search feature and discuss what changes would make the next improvement more useful.'),
(20,'Sprint Retrospective','An event for the Scrum Team to inspect and improve how it works','An event primarily for stakeholder feedback on product outcomes|An event primarily for approving the initial project charter|An event primarily for ranking all company investments','Remember: retrospect means look back to learn. The team identifies ways to improve effectiveness and quality.','The team notices that late testing caused rework and agrees to test earlier next Sprint.'),
(21,'Sprint Backlog','The Sprint Goal, selected Product Backlog items, and the actionable plan for delivering them','The complete ordered list of all future product improvements|The agreed quality standard that defines a completed Increment|The long-term objective describing the product’s future state','Remember: this belongs to the current Sprint and is adapted by Developers as they learn. It is not the whole product’s wish list.','For this Sprint, Developers track the chosen checkout work and their plan for achieving the Sprint Goal.'),
(21,'Product Goal','A longer-term objective describing a future state of the product','The quality standard for calling an Increment done|The single objective for one Sprint|The list of day-to-day tasks for the current Sprint','Remember: this gives direction to the Product Backlog. A Sprint Goal is a smaller, nearer-term objective.','The product aims to let students complete registration online without visiting an office.'),
(21,'Sprint Goal','The single objective for a Sprint that gives its work a shared purpose','The complete list of every desired product feature|The organization’s full portfolio investment strategy|The permanent quality standard for every Increment','Remember: the goal explains why the selected work matters. The detailed plan can change while the team keeps that purpose in view.','This Sprint’s goal is to let a student find available courses by department.'),
(21,'Increment in Scrum','A usable addition to the product that meets the Definition of Done and works with earlier increments','An unfinished task that has merely been started|A future feature request that has not been built|A schedule estimate without a usable result','Remember: it is usable, integrated work, not just a percentage of tasks completed. Done gives everyone a shared quality standard.','A tested search improvement works with the existing app and meets the team’s agreed quality requirements.'),
(28,'Strength in SWOT','An internal capability or advantage that supports the organization','An internal limitation that holds the organization back|An external condition that could help the organization|An external condition that could harm the organization','Remember: ask two questions: is it inside or outside, and does it help or hurt? A strength is inside and helpful.','Experienced staff who already know the technology are a strength the organization can use.'),
(28,'Weakness in SWOT','An internal limitation or disadvantage','An external favorable change|An internal capability that helps|An external danger to success','Remember: a weakness is inside the organization and makes success harder. This separates it from an external threat.','A lack of staff training is an internal weakness that can slow the project.'),
(28,'Opportunity in SWOT','An external condition the organization could benefit from','An internal skill the organization already has|An internal limitation that needs improvement|An external condition likely to cause harm','Remember: an opportunity comes from the environment outside the organization and could help if acted on.','A new grant program creates a chance to fund a useful campus technology project.'),
(28,'Threat in SWOT','An external condition that could harm the organization','An internal advantage the organization already has|An external chance to gain benefits|An internal lack of skills','Remember: a threat is outside and potentially harmful. An internal weakness may make the organization more vulnerable to it.','A new competitor offering a better service could draw customers away.'),
(69,'Fairness','Considering whether decisions and treatment are impartial and avoid unjust disadvantage','Hiding decision criteria so nobody can question them|Taking ownership of a decision without examining its effects|Explaining a process while ignoring unequal harm','Remember: being transparent about a decision does not by itself make the decision fair. You must examine how people are treated and affected.','A manager reviews whether an AI-assisted assignment process consistently disadvantages one group without a relevant reason.'),
(56,'Training an AI model','Adjusting a model using data so it learns patterns','Applying an already trained model to a new input|Approving a project charter for an AI system|Giving every generated answer a guarantee of accuracy','Remember: training changes the model through examples. Inference uses the trained model to produce a result; the two are different activities.','Examples of correctly labeled tickets are used to adjust a model before it classifies new tickets.'),
(58,'AI agent','A system that observes information and selects or performs actions toward objectives','Any stored document that mentions artificial intelligence|A model that is guaranteed to be correct|A system that must act without any limits or human oversight','Remember: an agent connects observations to actions. Its capabilities and allowed actions depend on its design and permissions.','A support agent reads a ticket, identifies the needed category, and routes it using an allowed tool.')
]
existing={v['term'] for v in d['vocab']}
for n,term,correct,wrong,why,example in rows:
 if term in existing:continue
 q=next(q for q in d['questions'] if q['number']==n)
 d['vocab'].append(dict(id=f'464-v{len(d["vocab"])+1:03}',source=n,section=q['section'],term=term,exp='',q=f'What is {term} in this chapter?',correct=correct,answer=correct,distractors=wrong.split('|'),teach=why,example=example))
# Give each project role its own explanation, rather than generic stakeholder feedback.
role_rows=[
('Sponsor','Supports the project and secures or authorizes resources',
'Primarily coordinates the team’s day-to-day project work|Primarily carries out the tasks that produce the deliverables|Primarily advocates for the project without necessarily having resource authority',
'Remember: resources include money, people, and equipment. A sponsor helps the project obtain organizational backing and resources, and can help resolve issues beyond the project manager’s authority. Sponsoring is different from coordinating every daily task.',
'A university leader backs a new registration system and authorizes its budget and staff support. That is the sponsor role.'),
('Champion','Actively advocates for the project and builds support for it',
'Must be the person with formal authority to approve the budget|Must perform all tasks that create the project’s result|Must chair the group overseeing the project',
'Remember: an advocate speaks up for an idea and helps others see its value. A champion promotes the project but does not necessarily have formal budget authority. One person can sometimes be both champion and sponsor.',
'A professor explains why the new registration system will help students and persuades departments to support it. That is championing the project.'),
('Project manager','Coordinates the project’s people, work, plans, and decisions to meet its objectives',
'Primarily advocates for an idea without coordinating its delivery|Primarily provides organizational funding rather than managing daily work|Primarily serves as the committee giving high-level oversight',
'Remember: coordinating means making sure connected pieces of work fit together. The project manager organizes planning, communication, dependencies, risks, and progress; they do not personally perform every specialist task.',
'The project manager checks that design is ready before coding begins, resolves a staffing conflict, and keeps everyone informed about the deadline.'),
('Project team','Performs the work needed to produce the project’s deliverables',
'Primarily authorizes organizational funding for the project|Primarily supplies high-level oversight as a governing committee|Primarily promotes the project without carrying out its delivery work',
'Remember: a deliverable is a result the project must produce, such as a working system or training materials. Team members contribute the skills and tasks that create those results. The manager coordinates their work.',
'Designers plan the screens, developers build them, testers check them, and trainers prepare users. Together they perform the project work.'),
('Steering committee','Provides high-level direction, oversight, and major decisions within its authority',
'Primarily performs the daily design, coding, and testing tasks|Primarily coordinates every team member’s daily task as one project manager|Primarily acts as an informal advocate without a governance role',
'Remember: a committee is a group of people. Steering means guiding the overall direction; oversight means checking that the project stays aligned with organizational goals. Its exact decision authority depends on the organization.',
'Leaders from several departments review major project issues and decide which priorities should guide the work. The project manager then coordinates the agreed direction.')
]
for term,correct,wrong,why,example in role_rows:
 v=next((v for v in d['vocab'] if v['term']==term),None)
 if v is None:
  v=dict(id=f'464-v{len(d["vocab"])+1:03}',source=9,section=1,term=term,exp='')
  d['vocab'].append(v)
 v.update(q=f'What is the role of the {term.lower()}?',correct=correct,answer=correct,distractors=wrong.split('|'),teach=why,example=example)
d['termCoverage']=[dict(term=v['term'],id=v['id'],section=v['section'],source=v['source']) for v in d['vocab']]
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
print('Direct term checks:',len(d['vocab']))
