"""Original entry-level interview curriculum. Sources support scope, not promised questions."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
D={'version':1,'reviewed':'2026-09-28','audience':'U.S. entry-level / May 2027 graduate','sources':[], 'tracks':[], 'modules':[], 'lessons':[], 'questions':[], 'interviews':[]}
def source(id,title,url,kind,note): D['sources'].append(dict(id=id,title=title,url=url,kind=kind,note=note))
source('onet','O*NET: Computer Systems Analysts','https://www.onetonline.org/link/summary/15-1211.00','Occupation evidence','Requirements, systems integration, troubleshooting, testing and user support appear across this occupation. Individual postings vary.')
source('support','O*NET: Computer User Support Specialists','https://www.onetonline.org/link/summary/15-1232.00','Occupation evidence','Useful for support-oriented IT analyst roles; not every analyst job is help desk work.')
source('deloitte','Deloitte: Case and scenario interview tips','https://www.deloitte.com/us/en/careers/join-deloitte/recruiting-tips/case-and-scenario-interview-tips.html','Employer interview guidance','Explains reasoning, assumptions, recommendations and next steps. Does not promise a particular question or round for your vacancy.')
source('capital','Capital One: Student and graduate interviews','https://www.capitalonecareers.com/en/student-and-grad-application-questions-answered-students-cdev','Employer interview guidance','Describes behavioral, case, job-fit and technical formats by program. Confirm your specific process with the recruiter.')
source('tdp','Capital One: Technology Development Program','https://www.capitalonecareers.com/elevate-your-tech-career-with-the-tdp-students-tech','Employer role example','This TDP includes software engineering rotations. A technology-program title alone does not mean a noncoding role.')
source('epic','Epic: Technical Solutions Engineering','https://careers.epic.com/jobs/technical-solutions-engineer/','Employer role example','Emphasizes troubleshooting and customer relationships; says specific programming expertise is not required for this role. This is not a rule for other employers.')
source('sc','ServiceNow: Associate Solution Consultant','https://careers.servicenow.com/jobs/744000063545800/associate-solution-consultant/','Employer role example','An early-career role example involving customer discovery and product demonstrations. Presales helps a customer evaluate a solution before purchasing it; postings and availability change.')
source('amazon','Amazon: Business Intelligence Engineer interview preparation','https://www.amazon.jobs/content/en/how-we-hire/bie-interview-prep','Employer interview guidance','SQL, analytics and behavioral preparation for BIE roles specifically. An adjacent data-heavy example, not the required interview for all business systems analysts.')
source('iiba','IIBA: Understanding requirements and designs','https://www.iiba.org/knowledgehub/the-business-analysis-standard/4-implementing-business-analysis/4-4-understanding-requirements-and-designs/','Professional standard','Requirements express needs; designs describe solutions. Provides a basis for our original business-analysis exercises.')
source('audit','ISACA: IT Audit Fundamentals','https://www.isaca.org/credentialing/it-audit-fundamentals-certificate','Professional curriculum','Covers auditing, controls, risk and IT environments. A knowledge reference, not a statement that you must buy a certification.')
source('nist','NIST: Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework','Technical reference','Risk-management outcomes across Govern, Identify, Protect, Detect, Respond and Recover; not a one-time linear checklist.')
source('cloud','Microsoft: Shared responsibility in the cloud','https://learn.microsoft.com/en-us/azure/security/fundamentals/shared-responsibility','Technical reference','Responsibility changes across cloud services. Customers still manage their data and identities.')
source('web','MDN: How the web works','https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works','Technical reference','Supports the client, server, DNS and web-request foundations. Our scenarios are original.')
source('http','MDN: Overview of HTTP','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview','Technical reference','Web requests and responses, including methods, headers and response status.')
source('sql','PostgreSQL: Joins between tables','https://www.postgresql.org/docs/current/tutorial-join.html','Technical reference','Relational joins; our small customer/order tables and practice queries are original.')
source('sqlagg','PostgreSQL: Aggregate functions','https://www.postgresql.org/docs/current/tutorial-agg.html','Technical reference','COUNT, grouping and the difference between row filtering and group filtering.')
source('scrum','The Scrum Guide','https://scrumguides.org/scrum-guide.html','Technical reference','Scrum roles, events and incremental work. Scrum is one framework, not a synonym for all agile work.')
source('security','CISA: Secure Our World','https://www.cisa.gov/secure-our-world','Technical reference','Basic security habits including multifactor authentication, phishing awareness and software updates.')
tracks=[
('all','Explore all paths',[],list(range(1,10)),'Start with shared foundations; then compare the role paths. Coding is conditional, not a universal requirement.'),
('it','IT & systems',['Technology Analyst','IT Analyst','Systems Analyst'],[1,2,3,4,5,8],'Prioritize troubleshooting, networks, accounts, systems, data and clear support communication. Some systems analyst jobs also require coding.'),
('ba','Business & technical analysis',['Business Systems Analyst','Technical Business Analyst'],[1,3,4,5,8],'Prioritize business needs, workflows, data, requirements, integrations and acceptance testing. Check the posting for SQL and tool depth.'),
('consult','Technology consulting',['Technology Consultant','IT Consultant','Associate Technology Consultant','Technical Consultant'],[1,2,3,4,5,6,8],'Prioritize structured problem solving, technical foundations, recommendations, delivery and client communication. Technical consultant can also mean a specialist coding role.'),
('solution','Solutions & implementation',['Solutions Consultant','Implementation Consultant'],[1,3,4,5,6,8],'Solutions consulting may mean presales discovery and demos. Implementation usually means configuring, testing, moving data and helping users adopt a purchased system.'),
('risk','Technology risk & audit',['Technology Risk Analyst','IT Risk Analyst','IT Auditor'],[1,2,3,7,8],'Prioritize risk, access, changes, evidence, controls and explaining findings. Audit evaluates controls; risk roles may help manage them.'),
('rotation','Technology programs',['Technology Rotational Program / Technology Development Program'],[1,2,3,4,5,8,9],'Read the actual rotations. Some programs rotate across IT/business functions; others are software-engineering programs with coding assessments.')]
for id,title,roles,mods,about in tracks:D['tracks'].append(dict(id=id,title=title,roles=roles,modules=mods,about=about))
for id,title,why in [
(1,'Start here: how workplace technology fits together','Understand what the people, software, devices and data actually do.'),
(2,'Troubleshoot without guessing','Narrow a problem using evidence, communicate impact and verify the fix.'),
(3,'Security, accounts & cloud','Explain who can access what, how to reduce risk and what cloud changes.'),
(4,'Data, SQL & useful numbers','Read tables, reason about joins and explain what a metric really measures.'),
(5,'Business needs → working systems','Turn a vague request into a testable change that users can adopt.'),
(6,'Consulting, demos & implementation','Understand a customer problem, compare options and recommend a practical next step.'),
(7,'Risk & IT audit','Connect a risk to a control, evidence and a defensible conclusion.'),
(8,'Tell your story & interview clearly','Practice truthful examples from class, jobs, clubs and everyday teamwork.'),
(9,'Coding track: only when the posting needs it','An introduction to coding-interview thinking for software-oriented programs; further coding practice is required.')]: D['modules'].append(dict(id=id,title=title,why=why))

def lesson(id,m,title,terms,teach,example,question,correct,wrong,why,interview,outline,sources):
    # Explanations are written per concept, never generated by repeating the answer.
    L=dict(id=id,module=m,title=title,terms=[dict(term=a,definition=b) for a,b in terms],teach=teach.split('|'),example=example,sources=sources)
    D['lessons'].append(L)
    D['questions'].append(dict(id=id+'-mc',lesson=id,kind='mc',prompt=question,answer=correct,options=[correct]+wrong,why=why))
    D['interviews'].append(dict(id=id+'-talk',lesson=id,prompt=interview,outline=outline,followup='What information would change your answer?',kind='Original practice prompt'))

lesson('system',1,'What is an IT system?', [('IT','Information technology: using computers and related systems to store, process and share information.'),('End user','The person using a tool to do their work, such as a cashier using checkout software.'),('System','Connected parts working together to do a job.')],
'A company needs to get work done: sell an item, pay an employee or answer a customer. An IT system helps people do that work. It includes more than a computer: people follow steps, software follows instructions, and data records what happened.|Imagine a cashier selling a shirt. The scanner reads an item code; the checkout application finds a price; a database stores the sale; a network carries messages between devices. A problem in any part can stop checkout.|An analyst asks what business task failed and who is affected before naming a technology fix. That prevents solving the wrong problem.',
'A store says “IT is broken.” Ask: can staff log in, scan items, accept payment, or print receipts? Each is a different action and points to different parts.',
'A cashier can log in but every card payment fails. What is the most useful first clarification?', 'Which payment action fails, for whom, and since when?', ['Which replacement laptop should we order?','Which programming language should we switch to?','Which new database product should we buy?'],
'You need to locate the failed business action before choosing equipment or software. A successful login already tells you that at least part of the system works.',
'Explain an IT system to a store manager who does not work in technology.', ['Start with a business task such as a sale.','Connect people, steps, software, devices and data.','Explain one failure and its effect without blaming a user.'], ['onet'])
lesson('hardware',1,'Hardware, operating system & application', [('Hardware','Physical equipment you can touch.'),('Operating system (OS)','Software that manages the device and lets applications use its resources.'),('Application','Software for a particular task, such as a browser or spreadsheet.'),('RAM','Random access memory: working space for active programs; not the same as long-term storage.')],
'The laptop is hardware. Windows or macOS is its operating system. Excel and your browser are applications that run on that operating system.|Think of a kitchen: equipment is hardware, the organizer coordinating access is like the operating system, and individual recipes are like applications. The analogy is limited, but it helps separate the jobs.|Storage keeps files when the device is turned off. RAM holds active working data. A slow laptop could have limited RAM, a busy processor, a nearly full drive or a slow network; “slow” alone does not identify the cause.',
'If a spreadsheet is slow but other applications work, investigate that file/application before concluding the whole laptop needs replacement.',
'Which comparison correctly separates RAM from storage?','RAM supports active work; storage keeps saved files.', ['RAM keeps saved files; storage only runs active programs.','RAM is the operating system; storage is an application.','RAM and storage are two names for internet bandwidth.'],
'Opening a file brings data into working memory. Saving writes data to persistent storage. A memory shortage and a full disk are different problems.',
'A user says their computer is slow. How would you narrow that down?', ['Ask which task, when it began and whether others are affected.','Compare applications and observe CPU, memory, disk and network usage.','Use evidence to choose a safe next test and verify with the user.'], ['support'])
lesson('web',1,'What happens when you open a website?', [('Client','A program requesting a service; your browser acts as a client.'),('Server','A system that responds to requests.'),('DNS','Domain Name System: finds address information associated with names.'),('HTTPS','HTTP carried over an encrypted TLS connection.')],
'You type a website name into a browser. The browser needs to find where to send its request. DNS helps resolve the name to an address. The browser then communicates with the service and asks for content.|The server responds with content or an error. Your browser uses the response to display the page. A page may require many requests for images, scripts and other resources.|This is a simplified path: caches and reused connections can skip some steps. “The website does not work” could mean name lookup failed, connection failed, login failed or the application returned an error.',
'A name-lookup error and a “403 Forbidden” response point to different stages. A 403 means a server responded but refused that request; it is not evidence that DNS failed.',
'What is DNS doing when your browser resolves a website name?', 'Finding address information for the name.', ['Checking whether your password is correct.','Rendering the page design on your display.','Giving your account permission to edit the site.'],
'A name such as a company website is convenient for humans. Address information lets software direct traffic. DNS does not decide what your signed-in account may do.',
'Walk me through opening a website, and name two places a failure can happen.', ['Describe name lookup, connection and request/response.','Separate a lookup failure from an application response.','Acknowledge caching and avoid assuming every failure is the internet connection.'], ['web','http'])
lesson('integration',1,'APIs & systems talking to each other', [('API','Application Programming Interface: a defined way for software to request data or actions from other software.'),('Integration','Connecting systems so they can exchange data or coordinate work.'),('JSON','JavaScript Object Notation: a common text format for structured data.')],
'An employee can click a screen. Software needs its own agreed way to ask another system for something. That is what an API provides: rules for what to send and what the response means.|For example, a store website asks an inventory service how many shirts remain. An API request identifies the item, and the response contains a quantity. JSON might represent it as {"item":"shirt","quantity":4}.|An integration must also handle missing fields, access permissions, timeouts and errors. Repeating a request that creates an order might create two orders unless the design prevents duplicates.',
'A successful network connection does not prove the order was accepted. Check the response and the resulting order record.',
'An order-creation request times out. What should you consider before retrying?', 'Whether the first request created an order and how duplicates are prevented.', ['Whether a timeout always means no order was created.','Whether every retry automatically replaces the previous order.','Whether JSON guarantees exactly one order will exist.'],
'The server may finish creating the order even if the response never reaches the client. A unique request identifier or a status check can help avoid duplicate work.',
'Explain an API integration and one failure you would plan for.', ['Use two named systems and a specific exchange.','Describe required fields and access.','Discuss response checks, retries and duplicate prevention.'], ['http','onet'])
lesson('triage',2,'A repeatable troubleshooting approach', [('Symptom','What you can observe going wrong.'),('Hypothesis','A possible explanation you can test.'),('Root cause','The underlying reason a problem occurred.'),('Escalate','Bring a problem to someone with the authority or expertise needed.')],
'Troubleshooting means narrowing possibilities with evidence. First learn the expected action, the actual result, the error, when it started and who is affected.|Next propose a cause and choose a low-risk test that could support or weaken that idea. Change one thing at a time when practical. Get authorization before disruptive changes and preserve useful evidence.|After an approved fix, repeat the original task with the user. Record the symptoms, tests and result. Restoring service can come before finding a deeper root cause; urgent incidents may require immediate escalation.',
'One person cannot print, but coworkers can. Check that person’s selected printer and queue before restarting the shared print server.',
'Why test one hypothesis with a controlled change?', 'It helps connect the observed result to the thing you changed.', ['It proves every similar device has the same root cause.','It eliminates the need to verify with the affected user.','It makes permission unnecessary for a disruptive change.'],
'If you change five settings at once, you may not know which mattered or which caused a new fault. A controlled test produces more useful evidence.',
'How would you troubleshoot an issue you have never seen?', ['Clarify scope and collect the exact symptoms.','Explain a testable hypothesis and a safe test.','Escalate with evidence, then verify and document the outcome.'], ['support','epic'])
lesson('network',2,'IP, DHCP, DNS & the default gateway', [('IP address','An address used to deliver data across IP networks.'),('DHCP','Dynamic Host Configuration Protocol: can give a device its network settings automatically.'),('Default gateway','A router a device can use to reach destinations outside its local network.'),('Wi-Fi','A way to connect wirelessly to a local network; it does not itself guarantee internet access.')],
'A laptop needs network settings to communicate. Its IP address identifies its network interface, a subnet prefix helps identify local destinations, and a gateway helps reach other networks. DHCP often supplies these settings.|DNS answers name questions. These are different jobs: having an IP address does not prove DNS works, and being connected to Wi-Fi does not prove the router has internet service.|Ask whether one device, one website or all users are affected. Compare working and failing devices. A failed ping alone is not proof a server is down: some systems block ping.',
'A laptop is connected to office Wi-Fi but cannot open the intranet by name. Check its settings and name resolution; do not assume the wireless connection is the cause.',
'Which service usually supplies a laptop with network settings automatically?', 'DHCP', ['DNS','HTTPS','An application login service'],
'DHCP can supply address, gateway and DNS-server settings. DNS then helps resolve names. They cooperate but perform different jobs.',
'A device connects to Wi-Fi but cannot reach a company site. What do you check?', ['Compare scope: one device, one site or many users.','Inspect address, gateway and DNS configuration and relevant errors.','Separate connectivity, name resolution and application access.'], ['web','support'])
lesson('incident',2,'Priorities, tickets & clear updates', [('Incident','An unplanned interruption or reduction in service quality.'),('Ticket','A recorded request or problem, including its status and history.'),('Impact','How much business work or how many people are affected.'),('Urgency','How quickly action is needed before consequences become serious.')],
'An incident is something failing now. A request might be routine work, such as asking for an approved software installation. A ticket records either so the work is not lost.|Prioritization considers both impact and urgency, using the organization’s rules. A payroll deadline may make a small number of affected users especially important. A loud complaint alone does not define the priority.|An update should say what is affected, what is known, what is being done and when the next update will arrive. Do not promise a repair time you cannot support.',
'“Checkout is failing in three stores. We are checking the payment service and have escalated to the on-call team. Next update in 15 minutes.”',
'Two issues compete: one user wants a cosmetic change; all stores cannot accept payments. What drives priority?', 'Business impact and urgency under the incident process.', ['The order in which the messages appeared only.','Which requester knows the most technical vocabulary.','Which issue can be closed with the shortest reply.'],
'Payment failure blocks business activity for many users. A cosmetic change usually has a different consequence and time sensitivity.',
'How would you communicate during an outage when you do not know the fix?', ['State verified impact and distinguish unknowns.','Name the current action and owner or escalation.','Commit to a next update rather than an invented fix time.'], ['support','onet'])
lesson('logs',2,'Logs, changes & evidence', [('Log','A record of events produced by a system.'),('Timestamp','The date and time attached to an event.'),('Rollback','Returning to an earlier version or configuration using an approved plan.')],
'A log is like a written history of what a system observed. It may record failed logins, application errors or service restarts. Look at the relevant time and timezone, affected request and exact message.|A change shortly before a failure is a clue, not proof. Compare what changed with the symptoms, test the hypothesis and consider other causes.|A rollback can restore a previous version, but it can also affect data or other changes. Follow the approved plan, coordinate with the owner and check recovery. Do not paste passwords or sensitive customer records into a ticket.',
'An application began failing at 10:02 after a release at 10:00. Check the release changes and matching error logs; do not declare the developer responsible based only on timing.',
'What does a failure occurring soon after a release establish?', 'A useful lead that needs more evidence.', ['Proof that the release caused every error.','Proof that the database lost all its records.','Proof that rollback has no possible side effects.'],
'Events close in time may be connected, but correlation does not establish the mechanism. Relevant error messages and comparisons strengthen or weaken the hypothesis.',
'What information would you include when escalating a technical incident?', ['Impact, start time/timezone and exact symptoms.','Tests already performed, their results and relevant recent changes.','Sanitized evidence, current status and the help needed.'], ['support','epic'])
lesson('identity',3,'Authentication vs authorization', [('Authentication','Checking who an account holder is.'),('Authorization','Deciding what that account may do.'),('MFA','Multifactor authentication: using different categories of proof, such as a password and a security key.'),('Least privilege','Giving only the access needed for an approved job.')],
'Logging in and having permission are different. Authentication checks identity; authorization checks whether the identified account may perform an action.|Picture an employee entering an office with a badge. Being recognized as an employee does not mean every locked room is open to them. A payroll system should restrict who can see salary information.|MFA adds another category of identity evidence. It does not automatically give permission or make every attack impossible. When someone leaves or changes jobs, review and remove access that is no longer needed.',
'You can sign in to the company portal but cannot edit payroll. Login may be working correctly while payroll editing is appropriately restricted.',
'A signed-in intern cannot edit payroll. Which concept controls the edit permission?', 'Authorization', ['Authentication','DNS resolution','Storage capacity'],
'The question is what an already identified account is allowed to do. Giving administrator access just to remove an error would bypass the intended access rules.',
'Explain authentication, authorization and least privilege with one example.', ['Separate identity checking from permission decisions.','Use a specific action such as viewing versus editing payroll.','Explain why access should match the job and be reviewed.'], ['security','cloud'])
lesson('security',3,'Risk, threats & everyday protection', [('Threat','Something that could cause harm, such as a malicious attacker.'),('Vulnerability','A weakness that could be exploited.'),('Risk','The possibility of harm, considered with its likelihood and impact.'),('Phishing','A deceptive message intended to trick someone into sharing information or taking an unsafe action.')],
'An attacker is a possible threat. An unpatched software flaw is a vulnerability. Losing customer information is a possible harmful outcome. Risk connects the possibility of that outcome with how serious it would be.|A control is an action or safeguard that reduces risk. Updating vulnerable software, restricting access and using MFA address different problems. No single safeguard removes all risk.|For a suspicious message, use the organization’s reporting process and verify unexpected requests through a trusted channel. Do not use contact details supplied only by the suspicious message.',
'A message says “Your manager needs gift cards immediately.” Verify with the manager using a known contact method instead of replying to the message.',
'Which is the vulnerability in this scenario: an attacker uses an unpatched software flaw to steal files?', 'The unpatched software flaw.', ['The attacker attempting the theft.','The loss of confidential files.','The estimate of likelihood and impact.'],
'The flaw is the weakness. The attacker is a threat actor, the theft is an adverse event, and risk concerns its possibility and consequences.',
'How would you explain a security risk to a nontechnical manager?', ['Name the business asset and plausible harm.','Separate the weakness from the threat and impact.','Recommend a proportionate control and explain remaining risk.'], ['security','nist'])
lesson('cloud',3,'Cloud services & shared responsibility', [('Cloud computing','Using computing resources provided as a service over a network.'),('IaaS','Infrastructure as a Service: renting basic compute, storage and network resources.'),('PaaS','Platform as a Service: a managed platform for building/running applications.'),('SaaS','Software as a Service: using a provider-managed application.')],
'Cloud means another organization provides computing services you can use. It is still powered by physical computers; you are changing how those resources are provided and managed.|With IaaS, you often manage the operating system on rented virtual machines. PaaS manages more of the platform. SaaS gives you a finished application. Exact responsibilities depend on the service.|The provider does not automatically decide which of your employees should see confidential files. You still need to manage identities, data and the settings under your control. Compare cost, reliability, security and business fit rather than saying cloud is always cheaper.',
'A company buys an online HR application. The vendor runs the application, but the company still decides who may view employee records.',
'In a SaaS HR application, which responsibility commonly remains with the customer?', 'Assigning appropriate employee access to its data.', ['Maintaining every physical server in the vendor facility.','Replacing the vendor’s building power equipment.','Designing all chips used by the cloud provider.'],
'The customer knows employees’ roles and data needs. Outsourcing infrastructure does not outsource all access decisions.',
'What changes, and what stays your responsibility, when a company uses cloud software?', ['Explain provider-managed services without saying computers disappear.','Identify customer data, accounts and configuration responsibilities.','Say the boundary depends on the service and agreement.'], ['cloud'])
lesson('recovery',3,'Backups, recovery & resilience', [('Backup','A separate recoverable copy of data.'),('RPO','Recovery Point Objective: the maximum targeted amount of data loss measured in time.'),('RTO','Recovery Time Objective: the targeted time to restore service.'),('Availability','Whether a service can be used when needed.')],
'A backup is useful only if you can restore what the business needs. A “backup succeeded” message is not the same as a successful recovery test.|RPO asks how far back recovered data may be. If the target is one hour, losing a full day of records misses the target. RTO asks how long the service may take to come back.|These are targets chosen for business needs, not guarantees. Restoring data, rebuilding systems and checking that users can work may all take time. Replication and backups serve different purposes: a bad deletion can be copied to a replica.',
'A store wants service restored within two hours and at most 15 minutes of lost orders. RTO is two hours; RPO is 15 minutes.',
'Which target limits how much recent data can be lost, measured in time?', 'RPO', ['RTO','The display refresh rate','The number of user accounts'],
'Recovery point refers to the point in time your recovered records reach. Recovery time concerns the duration of the outage.',
'How would you check whether a backup process meets a business need?', ['Ask for recovery time and data-loss targets.','Review backup scope and protection, then test a restore.','Verify usable service and data rather than relying only on a success message.'], ['nist','audit'])
lesson('tables',4,'Tables, keys & clean data', [('Database','An organized collection of data managed so it can be stored and retrieved.'),('Row','One record in a table.'),('Primary key','A value or set of values that uniquely identifies a row.'),('Foreign key','A field or fields referencing a key in another or the same table.')],
'A customer table can contain one row per customer. A primary key such as customer_id distinguishes customers even when two people have the same name.|An order table can store customer_id to connect each order to a customer. This relationship avoids copying every customer detail into every order.|Before trusting a report, check what each row represents. Missing identifiers, duplicates and inconsistent dates can change the result. Two orders from the same customer are not necessarily duplicate orders.',
'Customers: 1 = Ana, 2 = Bo. Orders: 101 belongs to 1; 102 also belongs to 1. Ana made two orders; she is still one customer.',
'Why join orders to customers by customer_id rather than customer name?', 'An identifier avoids ambiguity when names repeat or change.', ['A customer name is always guaranteed unique.','An identifier makes all missing values disappear.','Joining by an identifier automatically removes every duplicate order.'],
'Names are labels people can share or change. A stable unique key makes the intended relationship explicit, though data quality still needs checking.',
'How would you investigate duplicate customer records?', ['Define what counts as the same customer with the business owner.','Inspect identifiers, names and other relevant fields safely.','Do not delete records until dependencies and a correction plan are understood.'], ['sql','onet'])
lesson('join',4,'SQL joins: matching related records', [('SQL','Structured Query Language: a language for working with relational data.'),('INNER JOIN','Produces matching combinations of rows from both sides.'),('LEFT JOIN','Keeps every left-side row, with matching right-side rows or missing right-side values.')],
'A join connects records using a condition. With customers on the left and orders on the right, an inner join can show customers with matching orders. A left join can also keep customers who have no orders.|One customer with two matching orders produces two joined rows. That is expected when the relationship is one customer to many orders.|Choose the join based on the question. “Show every customer, even without an order” needs to preserve unmatched customers. A later filter can accidentally remove them, so read the whole query.',
'Customers Ana and Bo; two orders belong to Ana, none to Bo. An inner join gives two rows for Ana. A left join gives those two plus a row for Bo with NULL order fields.',
'For Ana (two orders) and Bo (no orders), how many rows does the described LEFT JOIN return?', '3', ['2','1','4'],
'Ana contributes two matching pairs. Bo contributes one preserved row with missing order values. Count joined records, not just distinct people.',
'Explain INNER JOIN versus LEFT JOIN using customers and orders.', ['Say which unmatched customers remain.','Explain why a customer can appear more than once.','Match the choice to the business question.'], ['sql'])
lesson('aggregate',4,'SQL filtering & counting', [('WHERE','Filters individual rows before grouping in a typical aggregate query.'),('GROUP BY','Collects rows into groups for calculations.'),('HAVING','Filters groups after aggregation.'),('NULL','A marker for missing or unknown data; not the same as zero.')],
'Use WHERE to keep relevant records, such as paid orders. GROUP BY customer_id then collects each customer’s records. COUNT can calculate a result per group. HAVING can keep only groups with at least two orders.|COUNT(*) counts rows. COUNT(column) counts non-NULL values in that column. This matters when a left join preserves a customer without an order.|Explain the business meaning of your query. A technically valid query can answer the wrong question if “paid,” the date range or the unit being counted is unclear.',
'For a left-joined row where Bo has NULL order_id, COUNT(*) counts that row but COUNT(order_id) is zero for Bo’s group.',
'After a LEFT JOIN, why use COUNT(order_id) to count actual orders for each customer?', 'It excludes the NULL order_id on an unmatched customer row.', ['It removes customers with no orders from every result.','It counts each customer name only once regardless of orders.','It turns missing order identifiers into a real order.'],
'Preserving a customer row does not create an order. Counting nonmissing order identifiers avoids treating that placeholder row as an order.',
'How would you find customers with at least two paid orders?', ['Filter to paid orders and define the relevant time range.','Group by customer identifier and count orders.','Filter groups to two or more; check duplicates and missing data.'], ['sqlagg'])
lesson('metrics',4,'Metrics, spreadsheets & percentages', [('Metric','A defined measurement used to understand something.'),('KPI','Key Performance Indicator: a metric chosen to track an important goal.'),('Denominator','The number you divide by in a fraction or rate.'),('Pivot table','A spreadsheet tool that groups and summarizes records.')],
'A number needs a meaning. “Ten failures” could be terrible out of ten attempts or rare out of ten thousand. A failure rate divides failed attempts by all relevant attempts.|Write the time period, included records and unit before calculating. In a spreadsheet, check data types, blanks and duplicates; a pivot table can summarize by team or month, and a lookup can match a key to another table.|Percentage points and percent change differ. Moving from 80% to 90% is a rise of 10 percentage points. Relative growth is (90 − 80) / 80 = 12.5%.',
'Out of 200 requests, 10 failed: 10 / 200 × 100 = 5%. Dividing by only the failed requests would answer a different question.',
'A success rate rises from 80% to 90%. What is the percentage-point increase?', '10 percentage points', ['12.5 percentage points','90 percentage points','1.125 percentage points'],
'Percentage points subtract the two percentages directly. The 12.5% calculation is relative growth compared with the original 80%, a different measure.',
'A manager asks for a dashboard. What do you clarify before building it?', ['Ask what decision or goal the dashboard supports.','Define each metric, population, date range and source.','Check quality and explain limitations before presenting conclusions.'], ['amazon','onet'])
lesson('requirements',5,'Turn “make it better” into a requirement', [('Stakeholder','A person or group affected by, interested in or able to influence the work.'),('Requirement','A statement of a need or capability to be satisfied.'),('Functional requirement','What a system must do.'),('Nonfunctional requirement','A quality or constraint, such as measurable response time or availability.')],
'“The app should be better” does not tell a team what to build or how to check it. Ask who uses it, what they are trying to do, what goes wrong and what improvement matters.|“A clerk can search orders by order number” describes a function. “Search returns within two seconds under an agreed workload” describes a measurable quality. Both need context.|A requirement describes a need. A design describes how a solution could meet it. Jumping straight to “buy this tool” may ignore a simpler process change.',
'Ask a support team to show the slow task. You may learn that copying order numbers between screens, rather than server speed, causes most delay.',
'Which is the clearest testable quality requirement?', 'Search returns within two seconds for the agreed test workload.', ['Search feels modern to everyone.','The application uses a popular technology brand.','The team should try to make search reasonably fast.'],
'A time threshold and stated conditions make the expected outcome checkable. Words like modern or fast require clarification.',
'A stakeholder says “we need a better system.” How do you respond?', ['Ask about the user, task, pain and desired outcome.','Observe the current process and check constraints.','Agree on specific, testable needs before selecting a design.'], ['iiba'])
lesson('process',5,'Map the process before changing software', [('Process','Related steps people or systems perform to produce an outcome.'),('As-is','How the work happens now.'),('To-be','How you propose the work should happen.'),('Handoff','Work or information passing from one person or system to another.')],
'A business process is the actual work: receive an order, check stock, pack it and ship it. A process map makes steps, decisions and handoffs visible.|First document the as-is process with the people who do it. Include exceptions, waiting and repeated entry, not only the ideal path. Then propose a to-be process that addresses an observed problem.|A software purchase does not automatically fix unclear ownership. Define who handles each step and how you will measure improvement.',
'Orders wait a day because nobody owns approval. A faster computer would not fix the missing approval responsibility.',
'Why observe the current process before recommending a new tool?', 'To find the actual bottleneck and avoid automating a misunderstood process.', ['To guarantee the current process never needs to change.','To remove the need to involve people doing the work.','To prove every delay is caused by old hardware.'],
'A delay may come from a decision, handoff or missing information. Observing the work helps match the solution to the cause.',
'How would you investigate a slow order-fulfillment process?', ['Map steps, actors, waits and exceptions with users.','Measure where time is spent and validate the cause.','Propose a change and compare results against a baseline.'], ['iiba','onet'])
lesson('uat',5,'Acceptance criteria, testing & UAT', [('Acceptance criteria','Specific conditions used to decide whether a change meets a need.'),('UAT','User Acceptance Testing: intended users or their representatives check whether the solution meets business needs.'),('Test case','Inputs, actions and expected results for checking behavior.'),('Defect','A mismatch between expected and actual behavior.')],
'Before building, agree on what success looks like. For an order search, criteria might cover a valid order, an unknown number and a user who lacks permission.|Developers test code and teams test integrations. UAT adds the business perspective: can intended users carry out realistic work correctly? It does not replace all other testing.|Record what you tried, expected and observed. When a test fails, describe the evidence and severity. “Looks good” without criteria is weak evidence.',
'Criterion: an unknown order number displays “No order found” without exposing another customer’s information. Test with a known nonexistent number and check the result.',
'What is UAT primarily checking?', 'Whether the solution supports the agreed business needs for intended users.', ['Whether the development team attended every meeting.','Whether the product has more screens than the old tool.','Whether all future software defects are impossible.'],
'Business users test meaningful tasks and acceptance criteria. Passing UAT is evidence of fit for those tested needs, not proof of perfection.',
'Write acceptance criteria aloud for a password-reset feature.', ['Identify the user and successful path.','Include an invalid/expired request and privacy or access concerns.','Describe observable outcomes that a tester can verify.'], ['iiba','onet'])
lesson('delivery',5,'Agile, releases & controlled changes', [('Agile','An approach emphasizing adaptation, collaboration and frequent delivery of useful outcomes.'),('Sprint','In Scrum, a fixed-length period of one month or less for producing progress toward goals.'),('Release','Making a version available to its intended users.'),('Change management','A controlled way to assess, approve, implement and review changes; context matters.')],
'Building a system usually involves understanding needs, designing, creating/configuring, testing, releasing and maintaining it. These activities can repeat rather than happen only once.|Agile work uses feedback to adjust. Scrum is one framework for that work. Agile does not mean no planning, documentation or controls.|A release still needs suitable testing, approval, communication and a recovery plan. When a stakeholder requests new scope, clarify its value and impact, then have the responsible people reprioritize.',
'A team can work in short iterations while still requiring review and testing before changes reach a payroll system.',
'A stakeholder adds a major request halfway through a delivery. What is a sound response?', 'Clarify its value and impact, then agree on priorities and tradeoffs.', ['Accept it without changing dates or scope expectations.','Reject it because iterative projects never change.','Skip testing so the original deadline cannot move.'],
'New work uses time and resources. Making the tradeoff visible helps stakeholders choose deliberately instead of silently reducing quality.',
'What does agile mean, and how would you handle a changing requirement?', ['Explain adaptation and feedback in ordinary language.','Distinguish agile from a specific framework such as Scrum.','Assess impact and agree priorities while keeping appropriate quality controls.'], ['scrum','onet'])
lesson('discovery',6,'Consulting starts with discovery', [('Client','The person or organization receiving your service.'),('Discovery','Learning the customer’s problem, context and needs before proposing a solution.'),('Constraint','A limit you must work within, such as time, budget or policy.')],
'A consultant helps a client understand or solve a problem. Starting with a product pitch can miss what the client actually needs.|Ask what outcome matters, who is affected, how the work happens today and what constraints apply. State assumptions rather than quietly treating guesses as facts.|Organize your thinking, compare options, make a recommendation and explain how you would validate it. Interview cases often assess this reasoning, not a memorized perfect answer.',
'A retailer asks for an AI chatbot. Discover whether the goal is shorter wait times, fewer repeat contacts or lower cost. Different goals may suggest different solutions.',
'What should you clarify first when a client requests a new tool?', 'The business problem and desired outcome.', ['The color of every screen before discussing the task.','The largest package the vendor is willing to sell.','The final implementation date before learning the scope.'],
'A tool is a possible solution, not the problem itself. Knowing the intended outcome lets you evaluate whether it will help.',
'A client wants to modernize its technology. How would you structure the first conversation?', ['Clarify the goal and current pain with examples.','Identify users, constraints, risks and success measures.','Summarize assumptions and propose the next discovery step.'], ['deloitte','epic'])
lesson('value',6,'Compare options with numbers and tradeoffs', [('Benefit','An improvement the organization expects from a change.'),('Cost','Resources spent, including implementation and ongoing operation.'),('ROI','Return on Investment: in a simple model, net benefit divided by cost.'),('Assumption','Something treated as true for analysis that needs validation.')],
'Compare options against the same business goal. Include implementation effort, recurring costs, benefits, risks and the option of making a smaller change.|For a simple one-year example, suppose benefits are $60,000 and total costs are $40,000. Net benefit is $20,000, and simple ROI is $20,000 / $40,000 = 50%. State the time period and assumptions.|Time saved is not automatically cash saved. Staff might use freed time on other work without reducing payroll. A strong recommendation explains the mechanism, uncertainty and what you would measure in a pilot.',
'A tool saves estimated staff time but requires training and integration. Include those costs and validate the time savings with real users.',
'One-year benefits are $60,000 and costs are $40,000. What is simple net ROI?', '50%', ['150%','66.7%','20%'],
'First subtract costs: 60,000 − 40,000 = 20,000. Divide net benefit by cost: 20,000 / 40,000 = 0.5. Multiply by 100 for 50%.',
'How would you decide whether to buy or build a solution?', ['Compare needs, time, total cost, security and integration.','State assumptions and consider vendor dependence or maintenance.','Recommend a choice with a validation step and explicit tradeoffs.'], ['deloitte','onet'])
lesson('demo',6,'Solutions consulting: show a useful workflow', [('Presales','Helping a potential customer evaluate a solution before a purchase.'),('Demo','A demonstration of how a product handles a relevant task.'),('Objection','A customer’s concern or reason a proposed choice may not fit.')],
'A solutions consultant may help a sales team explain and demonstrate a technical product. This is different from promising every feature or only installing software after purchase.|Begin with the customer’s situation. Demonstrate a short workflow that addresses the need, explain the business result and ask whether it fits. A list of every feature can hide the value.|If asked about a capability you cannot verify, say what you know, record the question and follow up with a reliable answer. Do not invent a feature to keep the demo moving.',
'For a support manager worried about lost requests, show one request being captured, assigned and tracked to resolution.',
'A customer asks for an integration you have not verified. What should you say?', 'Explain the uncertainty and confirm the capability with the appropriate source.', ['Promise support because most modern systems probably connect.','Say the feature exists if the demo audience seems interested.','Treat a planned feature as already available to every customer.'],
'A buying decision may depend on the answer. Clear uncertainty and a concrete follow-up protect the customer from a false expectation.',
'Give a two-minute demo plan for a support-ticket tool.', ['Name the customer problem and one relevant workflow.','Show the workflow and connect it to an outcome.','Check understanding and record unanswered questions honestly.'], ['sc'])
lesson('implementation',6,'Implementation, migration & adoption', [('Configuration','Choosing supported settings to adapt a system.'),('Customization','Changing or extending behavior beyond standard settings.'),('Migration','Moving data or functionality from an old environment to a new one.'),('Adoption','People actually using the new approach effectively.')],
'Implementation turns an agreed solution into something users can work with. It can involve configuration, integrations, moving data, testing, training and support.|For data migration, map old fields to new fields, check quality, rehearse with a copy, compare results and plan the cutover. Cutover is the switch from old to new. Keep an approved recovery plan.|A live system is not automatically a successful change. Users need to know how to do their jobs, and the team should check adoption and business results after launch.',
'Before moving customer records, compare record counts, required fields and sample values. Matching counts alone will not catch names placed in the wrong field.',
'Why is matching record counts insufficient to validate a migration?', 'The records could still contain wrong or misplaced values.', ['Equal counts prove all permissions and workflows work.','Equal counts guarantee no duplicate customer identifiers.','Counts determine whether every user understands the system.'],
'Counts check quantity, not the meaning or correctness of each field. Use field checks, reconciliation and realistic workflow tests too.',
'How would you help roll out a new business application?', ['Plan requirements, settings, integrations and migration validation.','Test with users and prepare training, cutover and recovery.','Monitor adoption and issues after launch.'], ['onet','epic'])
lesson('controls',7,'Risks & controls: what could go wrong?', [('Control','A safeguard or activity intended to reduce risk.'),('Preventive control','A control intended to stop a problem before it occurs.'),('Detective control','A control intended to identify a problem or deviation.'),('Residual risk','Risk remaining after controls are applied.')],
'A risk statement should connect a cause to a possible event and business impact. For example: unreviewed access could allow an ex-employee to view confidential records.|A control addresses that possibility. Removing access on departure helps prevent misuse. Reviewing access logs may help detect misuse. Controls have owners and should leave useful evidence.|Risk management helps decide and monitor responses. Audit evaluates evidence about whether controls are designed and operating as intended. A checklist tick without support is not the same as a justified conclusion.',
'A locked door reduces unauthorized entry, while an access-log review can help identify unusual entry. Different controls work at different points.',
'Which is a detective control?', 'Reviewing access logs for unexpected activity.', ['Blocking access until approval is granted.','Requiring permission before a payment is released.','Disabling a departed employee’s account promptly.'],
'The log review looks for events that have occurred. Approval gates and timely account removal are intended to prevent unauthorized actions.',
'Describe a risk and a control in plain language.', ['Name what could happen and why it matters.','Explain how a specific control reduces that possibility or impact.','Describe ownership, evidence and risk that remains.'], ['audit','nist'])
lesson('accessaudit',7,'Access reviews & separation of duties', [('Access review','Checking that users still have appropriate permissions.'),('Segregation of duties (SoD)','Separating incompatible responsibilities to reduce error or abuse.'),('Population','The full set of items in scope for a test.'),('Evidence','Information supporting a conclusion.')],
'An access review asks whether the right people have the right permissions now. Compare accounts to current roles, approvals and departures. A list of names alone does not show that someone reviewed it.|Separating duties can prevent one person from both creating a vendor and approving payment to that vendor. It reduces a conflict, although exceptions need assessment and other controls.|For an audit test, define the period and complete population, choose a justified sample when appropriate, inspect evidence and document exceptions. A few convenient examples do not prove every account is correct.',
'To test removal of leavers’ accounts, connect departure dates to account-disable timestamps and the policy’s required timing.',
'What is stronger evidence of timely account removal?', 'Departure dates linked to disable timestamps and the applicable timing rule.', ['A manager saying access is generally handled carefully.','A screenshot of one active employee’s desktop.','A list of software licenses without employee status.'],
'The dates and rule let you compare what should have happened with what actually happened. A general assurance does not establish timing.',
'How would you test whether departed employees lose access on time?', ['Define the policy, systems and period in scope.','Obtain a complete leaver population and reliable disable records.','Compare timing, investigate exceptions and document the conclusion.'], ['audit'])
lesson('changeaudit',7,'IT general controls & application controls', [('ITGC','IT General Controls: controls over the wider IT environment, often including access, changes and operations.'),('Application control','A control built into or around a particular business application or transaction.'),('Change approval','Authorization for a planned system change.')],
'General IT controls help support a reliable environment. Examples include access administration, controlled software changes and operational recovery procedures.|Application controls target particular processing. A system refusing an invoice without required fields is an application control. These categories connect: a good application check can be undermined if unauthorized people can alter it.|For a change, examine whether relevant approval, testing and deployment evidence match the actual release. An approval dated after deployment may need investigation; follow the organization’s emergency-change rules rather than assuming all exceptions are identical.',
'A tested release with appropriate approval supports controlled change. A ticket title saying “approved” without a dated decision is weaker evidence.',
'Which example is an application control rather than a general change-management control?', 'An invoice form rejects a missing required supplier identifier.', ['Software releases require approval before deployment.','Production code changes have documented test results.','Only approved staff can deploy production releases.'],
'The invoice check validates a particular transaction. The other choices govern the process for changing systems more broadly.',
'What evidence would you inspect for a production change?', ['Identify the change, policy and relevant period.','Link approvals and testing to the deployed version and timing.','Investigate exceptions, including any emergency-change process.'], ['audit'])
lesson('findings',7,'Explain an audit finding without exaggeration', [('Criteria','The rule or expectation used for evaluation.'),('Condition','What the evidence shows actually happened.'),('Remediation','Action to correct a problem or reduce its risk.'),('Governance','How responsibilities, direction and oversight are established.')],
'A useful finding separates the expected rule from observed facts. Explain the gap, why it matters and a practical response. Do not turn one exception into a claim that every system failed.|For example, the policy requires access removal within a defined time, but one sampled account remained active longer. Investigate the cause and scope. State what your testing supports and what it does not.|NIST CSF 2.0 organizes cybersecurity outcomes into Govern, Identify, Protect, Detect, Respond and Recover. These functions work together continuously; they are not six tasks completed once in order.',
'A finding can recommend a named owner, a due date and a later check that the fix works. Management owns the remediation; audit evaluates evidence.',
'What makes an audit finding defensible?', 'It links the rule, observed evidence, risk and recommended action.', ['It uses the strongest possible wording regardless of sample size.','It assumes one exception proves every account is compromised.','It omits the criterion so the report stays short.'],
'Readers need to see why an observed gap matters and how the conclusion follows from evidence. Unsupported certainty weakens the finding.',
'How would you explain an access-control exception to management?', ['State the rule and exactly what was observed.','Explain the business risk without claiming unproven harm.','Agree on ownership and corrective action, then plan verification.'], ['audit','nist'])
lesson('intro',8,'Tell me about yourself: a relevant introduction', [('Evidence','A concrete example that supports a claim about your skills.'),('Role fit','How your interests and demonstrated abilities connect to the job.')],
'For an entry-level introduction, connect where you are now, an example of what you can do and why this role interests you. You do not need a long life story.|As a May 2027 graduate, you can use a class project, part-time job, club or personal project. Name your actual contribution. “We built an app” becomes more useful when you explain what you designed, tested or investigated.|Adapt the connection to the role: a support job values troubleshooting and user communication; a business analyst job values clarifying needs. Be specific without pretending student work was paid client work.',
'Outline: “I graduate in May 2027. In [real project], I was responsible for [specific action]. I learned [relevant skill], and I’m interested in this role because [reason tied to the work].”',
'Which is the strongest entry-level claim?', 'A specific contribution you can explain and demonstrate from a real project.', ['A title you did not hold that sounds closer to the vacancy.','A list of tools you have never used but recognize.','A claim that your group’s entire result was your individual work.'],
'Interviewers can ask follow-ups. A concrete, truthful example gives you details to discuss and shows how you work.',
'Tell me about yourself and why you want this role.', ['State your May 2027 graduation and relevant direction briefly.','Give one true example with your own contribution.','Connect that evidence to the actual role rather than every technology job.'], ['capital','amazon'])
lesson('star',8,'Behavioral answers with STAR', [('STAR','Situation, Task, Action, Result: a structure for explaining a real experience.'),('Behavioral interview','An interview asking about how you handled past situations.')],
'A behavioral question might ask about a disagreement, mistake or difficult deadline. Pick one real event. Situation gives the setting; Task explains your responsibility; Action describes what you personally did; Result explains the outcome.|Spend most of the answer on your actions and reasoning. Say “we” for team outcomes and “I” for your contribution. Use numbers only if you actually measured or can honestly support them.|A result can include a lesson and a change in how you work. A story does not have to end perfectly to show responsibility and growth.',
'A group missed a milestone. Explain how you identified dependencies, agreed owners and updated the plan; then state the real outcome and what you would change next time.',
'Which part of STAR should explain what you personally did?', 'Action', ['Situation','Task','Result'],
'The setting and assignment provide context. The action section is where the interviewer can evaluate your decisions and behavior.',
'Tell me about a time you disagreed with a teammate.', ['Describe one real disagreement and the shared goal.','Explain how you listened, used evidence and acted respectfully.','State the actual outcome and a lesson without blaming or inventing numbers.'], ['amazon','capital'])
lesson('unknown',8,'Answer when you do not know', [('Clarifying question','A question that resolves missing information or ambiguity.'),('Assumption','A stated condition used while reasoning when information is missing.')],
'An interview is not only a memory test. When you do not know, separate what you understand from what you need to verify. Ask a focused question and reason through a safe next step.|For example: “I haven’t configured that product. I would first check the exact error and scope, then use the vendor documentation and ask the appropriate owner before making a change.”|Do not invent a command or claim certainty. Explaining how you would learn and validate can show judgment, especially in entry-level roles.',
'If asked about an unfamiliar tool, connect to a real related skill without claiming hands-on experience you do not have.',
'What is a strong response to an unfamiliar technical problem?', 'State the gap, clarify the problem and explain a safe way to investigate.', ['Invent a command so you appear decisive.','Claim you used the product because you read its name.','Change production settings immediately to discover what happens.'],
'Clear limits plus a reasoned investigation show trustworthiness and problem-solving. Guessing confidently can create real risk.',
'What would you do if a client asked a question you could not answer?', ['Be clear about what you know and do not know.','Clarify the need and identify a reliable source or expert.','Set a realistic follow-up and validate the answer before giving it.'], ['deloitte','epic'])
lesson('jobplan',8,'Read the posting & prepare your evidence', [('Required qualification','A condition the employer says candidates must meet.'),('Preferred qualification','An additional characteristic the employer would like.'),('Portfolio','Examples of your actual work that you can explain.')],
'A title does not define the full job. Read the work, qualifications, tools, location and start-date requirements. A “technology analyst” may focus on support, data or software depending on the employer.|For each important responsibility, match one real example or identify a learning gap. Prepare to explain the goal, your work, a challenge, testing and what you learned. Do not memorize a story disconnected from the posting.|For a May 2027 start, monitor graduate openings during fall 2026 and continue through spring; schedules vary. Confirm eligibility and start dates on each posting. Ask the recruiter about interview formats rather than assuming all firms use the same process.',
'If a posting asks for SQL, prepare a small dataset and explain a query. If it emphasizes audit, prepare a risk/control/evidence example instead.',
'What should determine how much coding preparation a rotational-program applicant needs?', 'The actual program responsibilities and assessment requirements.', ['The word technology in the title by itself.','The assumption that every rotation is software engineering.','The assumption that graduate programs never assess coding.'],
'Programs can have very different rotations. The posting and recruiter provide the relevant evidence; a broad label is not enough.',
'Why this company and this role?', ['Identify a specific responsibility or business problem that interests you.','Connect it to truthful evidence of your skills and learning.','Ask an informed question about work, support or success in the role.'], ['capital','tdp','onet'])
lesson('code',9,'Coding interviews: explain before you type', [('Algorithm','A sequence of steps for solving a problem.'),('Input','Information a program receives.'),('Output','The result a program produces.'),('Edge case','An unusual or boundary input that may expose a flaw.')],
'For a software-oriented program, you may need to write and test code. This introduction helps you reason, but multiple-choice practice is not a substitute for actually coding.|Start by clarifying the input and expected output. Work a small example by hand. Explain a simple approach, implement it, then test ordinary and boundary cases.|For finding duplicate identifiers, ask whether you should return all repeated values or merely say that a duplicate exists. That changes the required output.',
'Input [2, 5, 2]. If the task is “does any value repeat?”, the answer is true. If the task is “list repeated values once,” the answer is [2].',
'What should you clarify before solving “find duplicates”?', 'What result is required and how duplicates should be represented.', ['Which variable name will impress the interviewer most.','Whether testing can be skipped for short inputs.','Whether every input is guaranteed nonempty without asking.'],
'A correct algorithm must match the requested behavior. Two sensible interpretations can produce different valid-looking outputs.',
'Explain how you would find repeated values in a list.', ['Clarify the expected output and constraints.','Walk through a simple approach with an example.','Discuss tests and how time and memory grow; practice implementing it separately.'], ['tdp'])
lesson('complexity',9,'Efficiency & testing basics', [('Time complexity','How the amount of work grows as input size grows.'),('O(n)','Work growing roughly in proportion to input size.'),('O(n²)','Work growing roughly with the square of input size.'),('Unit test','A focused check of a small piece of behavior.')],
'If you scan a list once, doubling the list roughly doubles the work: linear growth, often written O(n). Comparing every item with every other item can grow quadratically, O(n²). These describe growth, not exact seconds.|A set of previously seen values can often find duplicates in expected linear time, using extra memory. The tradeoff matters: faster approaches may store more information.|Test empty input, a single item, no duplicates and repeated values. Explain why each test matters. Actual complexity depends on the operations and data structures used.',
'For a duplicate detector, [] should not report a duplicate; [7,7] should. Those two tests check different behaviors.',
'What does O(n) describe?', 'How work grows with input size, not an exact runtime in seconds.', ['A promise that code finishes in one second.','The exact memory address of every element.','A guarantee that all programming languages run equally fast.'],
'Growth notation abstracts away many machine details. It helps compare approaches as inputs become larger, but does not predict an exact clock time.',
'How would you test and improve a simple duplicate detector?', ['Test empty, single, unique and repeated inputs.','Explain a straightforward comparison approach.','Compare a set-based approach and its memory tradeoff.'], ['tdp'])

# Tappable sentence cards and genuine sequence tasks: original practice, no typed responses.
def blank(id,l,p,answers,extra,why):D['questions'].append(dict(id=id,lesson=l,kind='blank',prompt=p,answer=answers,bank=answers+extra,why=why))
def sort(id,l,p,items,why):D['questions'].append(dict(id=id,lesson=l,kind='sort',prompt=p,answer=items,bank=items,why=why))
blank('identity-fill','identity','____ checks who you are; ____ controls what you may do.',['Authentication','Authorization'],['DNS','Migration'],'Identity verification and permission decisions answer different questions. A valid login does not grant every permission.')
blank('network-fill','network','____ supplies network settings; ____ resolves names; a ____ helps reach other networks.',['DHCP','DNS','default gateway'],['web browser','spreadsheet'],'These three jobs cooperate. An automatically assigned address does not prove that name resolution or routing works.')
blank('recovery-fill','recovery','____ is the target for restoration time; ____ is the target for data loss measured in time.',['RTO','RPO'],['ROI','API'],'Remember time-to-return for RTO and recovered point in time for RPO. Both targets come from business needs.')
blank('risk-fill','security','A weakness is a ____; something that could exploit it is a ____.',['vulnerability','threat'],['backup','metric'],'A flaw and a possible source of harm are different. Risk considers the possibility and consequences of harm.')
blank('join-fill','join','Keep customers without orders with a ____; keep only matching pairs with an ____.',['LEFT JOIN','INNER JOIN'],['GROUP BY','ORDER BY'],'A left join preserves unmatched left-side rows. An inner join needs a match on both sides.')
blank('sql-fill','aggregate','Filter rows with ____; collect groups with ____; filter calculated groups with ____.',['WHERE','GROUP BY','HAVING'],['ORDER BY','LEFT JOIN'],'Rows and groups are different levels. A group count is available after the grouping calculation.')
blank('process-fill','process','The current workflow is ____; the proposed future workflow is ____.',['as-is','to-be'],['UAT','SaaS'],'Describe real current work first, then compare the proposed change to its actual problems.')
blank('controls-fill','controls','An approval gate is usually ____; reviewing a log for suspicious activity is ____.',['preventive','detective'],['a database key','a release'],'An approval gate tries to stop an unauthorized action. A review looks for evidence of activity that occurred.')
blank('value-fill','value','Simple ROI = (____ − ____) ÷ cost × 100.',['benefits','costs'],['users','hours'],'Subtract costs to get net benefit, then divide by the investment cost. Use the same time period for the amounts.')
blank('hardware-fill','hardware','Physical equipment is ____; a device manager such as Windows is an ____; Excel is an ____.',['hardware','operating system','application'],['API','metric'],'The physical device, resource-managing software and task-specific software are different parts of the same working system.')
sort('web-order','web','Build this simplified first visit to an HTTPS website (assume no cached address or open connection).',['Resolve the name','Establish a secure connection','Send the HTTP request','Receive the response','Display the content'],'The browser first needs an address and connection before sending the request. Real pages can reuse connections and make many requests.')
sort('trouble-order','triage','Order this ordinary troubleshooting workflow (urgent escalation may happen sooner).',['Clarify impact and symptoms','Form and test a hypothesis','Plan an approved fix','Apply the fix','Verify and document'],'Evidence guides the fix. Approval and impact review come before a disruptive action; verification confirms the original task works.')
sort('star-order','star','Build the STAR answer structure.',['Situation','Task','Action','Result'],'Give just enough context, identify your responsibility, explain your own actions, then state the true outcome and lesson.')
sort('migration-order','implementation','Arrange this simplified planned data migration.',['Map fields and inspect data','Rehearse the migration','Validate rehearsal results','Perform approved cutover','Verify and support users'],'A rehearsal and validation expose problems before the live switch. Verification and user support continue after cutover.')
sort('case-order','discovery','Build a clear recommendation for a case interview.',['Clarify the goal','State assumptions and analyze','Compare practical options','Recommend with tradeoffs','Propose validation and next steps'],'Analysis needs a goal. A recommendation should follow evidence and lead to an actionable next step; real conversations can loop back.')
for l in D['lessons']:
    for term in l['terms']:
        name=term['term']
        # Build selected useful abbreviation expansions, without unnatural ordering of concepts.
        exp={'API':'Application Programming Interface','DNS':'Domain Name System','DHCP':'Dynamic Host Configuration Protocol','SQL':'Structured Query Language','MFA':'Multifactor Authentication','UAT':'User Acceptance Testing','RPO':'Recovery Point Objective','RTO':'Recovery Time Objective','KPI':'Key Performance Indicator','ROI':'Return on Investment','ITGC':'IT General Controls','SaaS':'Software as a Service','IaaS':'Infrastructure as a Service','PaaS':'Platform as a Service','JSON':'JavaScript Object Notation'}.get(name)
        if exp: sort('expand-'+name.lower(),l['id'],'Build what '+name+' stands for.',exp.split(),term['definition'])
(ROOT/'dist/career-content.json').write_text(json.dumps(D,indent=2,ensure_ascii=False)+'\n')
print(len(D['lessons']),'lessons;',len(D['questions']),'practice activities;',len(D['interviews']),'interview prompts')
