import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];p=ROOT/'dist/cis304-content.json';d=json.loads(p.read_text())
v=[]
def term(name,meaning,why,wrong,source,exp=''):
 v.append(dict(id=f'304-v{len(v)+1:02}',term=name,exp=exp,answer=meaning,teach=why,correct=meaning,distractors=wrong.split('|'),source=source,section=d['questions'][source-1]['section'],q=f'What does {name} mean?'))
term('Data','Raw individual facts before interpretation','A list of sales amounts is data. Organizing them into a useful sales report produces information.','A reasoned decision about future action|The ability to apply experience|Only the rules followed by employees',1)
term('Information','Data processed or organized into meaning','The context matters: “30” is a fact; “30 orders sold today” has a useful meaning.','Uninterpreted facts only|Physical computing equipment|A judgment about which goal to pursue',1)
term('Knowledge','Understanding that lets you apply information','Knowing how sales patterns affect stock helps you use a report rather than simply read its numbers.','Any number stored in a database|A cable connecting computers|The money left after costs',1)
term('Wisdom','Judgment used to assess situations and choose sensible action','You consider consequences and trade-offs before deciding, rather than assuming all information points to one automatic answer.','Every raw fact collected|The storage space of a computer|A formatted report without a decision',1)
term('Hardware','Physical computing equipment','A scanner can be touched. Its program cannot: that program is software.','Instructions executed by computers|Agreed steps for doing work|Facts about a transaction',4)
term('Software','Instructions and programs run by computers','The program tells equipment what to do. It needs hardware to execute those instructions.','The physical processor itself|People operating a system|Only paper procedures',5)
term('RAM','Temporary working memory used by active programs','Work currently being used goes in RAM; saved files belong in persistent storage.','Permanent storage that keeps all files without power|A processor that executes instructions|An output screen',4,'Random Access Memory')
term('CPU','The processor that executes computer instructions','The CPU performs computation; RAM holds current work and storage keeps saved files.','The permanent storage drive|A networking cable|The display used to show results',4,'Central Processing Unit')
term('IS','People, processes, data, hardware, and software organized to handle information','An IS includes human work and procedures, not only a computer application.','Only hardware connected to a network|Only the data in one file|Only an organization’s long-term plan',2,'Information System')
term('DIKW','Data → Information → Knowledge → Wisdom','The model moves from facts toward understanding and judgment.','Data → Integration → Knowledge → Workflow|Design → Information → Knowledge → Work|Data → Information → Workflow → Knowledge',1,'Data Information Knowledge Wisdom')
term('Business strategy','The broad plan for goals and competitive advantage','It sets direction so process and technology choices serve business goals.','A record of one customer payment|A physical network layout alone|The daily steps of one transaction',7)
term('Business model','How a business creates, delivers, and captures value','It describes the offer, customers, and way of earning money.','Only who reports to whom|Only the computer system design|Only a measure of labor efficiency',9)
term('Cost leadership','Competing through lower costs','Lower operating costs can support competitive prices and sustainable margins.','Competing only through unique features|Setting high prices regardless of value|Increasing expenses to maximize input',7)
term('Differentiation','Competing through offerings customers value as distinct','A customer chooses a custom product or special service because the difference matters to them.','Making every offering identical to competitors|Competing solely through lower costs|Separating all department databases',7)
term('Stakeholder','A person or group affected by or interested in the work or result','Employees, customers, and managers may care about different outcomes in the same process.','Only the owner of computer hardware|Only the person writing software|A record of inventory levels',13)
term('DSRP','Distinctions, Systems, Relationships, Perspectives','Use it to examine boundaries, parts and wholes, interactions, and viewpoints.','Data, Systems, Resources, Processes|Decisions, Strategy, Relationships, Projects|Distinctions, Software, Results, Productivity',11,'Distinctions Systems Relationships Perspectives')
term('Input','A resource or item that goes into a process','An order, ingredient, labor hour, or piece of information can be an input.','Only the finished result|Only the final customer payment in every process|The comparison between actual and planned output',12)
term('Output','The result produced by a process','Outputs may be goods, completed services, information, or records.','Every resource consumed before work starts|Only a computer screen in all contexts|The steps followed to do the work',12)
term('Actor','A person or system performing an activity','A cashier and an automated payment system can both be actors in a process model.','Only an outside customer|A diagram’s arrow showing sequence|A resource that never performs an action',12)
term('Handoff','Transfer of work or responsibility between participants','When sales passes an order to the warehouse, the next team becomes responsible for its step.','A measurement of output per hour|An organization’s overall strategy|A duplicate copy that no other team receives',13)
term('As-is model','A model of the process as it currently works','You need to understand current work before identifying what to change.','The proposed future process|The hardware purchased next year|A list of goals with no activities',13)
term('To-be model','A model of the proposed future process','It shows the intended new way of doing work, which still needs implementation and evaluation.','The current process before changes|A record of historical transactions only|An employee reporting chart only',13)
term('UML','A standardized visual modeling language','Activity diagrams can show activities, decisions, and flow using shared symbols.','A financial measurement formula|An enterprise software vendor|A method that forbids diagrams',13,'Unified Modeling Language')
term('Project','A temporary effort creating a unique result','Developing a new ordering system ends; repeatedly processing orders continues.','An indefinitely repeated operational routine|A permanent department by definition|A collection of hardware with no objective',14)
term('Procurement','Obtaining needed goods or services from suppliers','The organization is the buyer: it requests resources, receives them, and pays.','Selling goods to a customer|Transforming raw materials into finished products|Preparing financial statements only',18)
term('Production','Transforming resources into goods or completed services','For a salon, doing a haircut is production of a service; it need not be a factory.','Buying all required resources from suppliers|Recording only financial transactions|Collecting a customer’s payment without doing the work',18)
term('Fulfillment','Meeting a customer order by delivering goods or services and handling payment','The organization is the seller. Its work follows the customer order toward completion.','Obtaining supplies as a buyer|Only recording financial statements|Only recruiting employees',18)
term('Accounting','Recording, checking, and reporting financial activity','Sales and purchasing create financial events; accounting turns those events into reliable records and reports.','Only making physical products|Only negotiating supplier orders|Only delivering the customer’s order',18)
term('Purchase requisition','An internal request to obtain goods or services','An employee asks the organization to authorize a purchase before it orders from a vendor.','An order sent to a selected external vendor|A bill sent by a vendor|A record of a customer sale',19)
term('Purchase order','A buyer’s order sent to a selected vendor','The buyer asks the vendor to supply specified goods or services; an internal request is a requisition.','An internal request before supplier ordering|The vendor’s request for payment|The seller’s financial statement',19)
term('Sales order','A record managing the seller’s handling of a customer order','The seller tracks what was ordered and what must be supplied. It is not the same as asking the customer to pay.','An employee’s internal purchase request|A vendor bill received by the buyer|A final statement of all business profit',19)
term('Invoice','A document requesting payment for supplied goods or services','The seller sends a sales invoice; the buyer receives that document as a vendor invoice. An invoice is not automatically proof that payment occurred.','An internal request for purchasing approval|Only a list of employees|A guarantee that the customer has already paid',19)
term('PI','Initial planned input','This is the resource amount expected before doing the work, such as a budget of ten hours.','Actual input used|Initial planned output|Actual output achieved',15,'Planned Input')
term('AI','Actual input used','In these formulas AI means actual input, not artificial intelligence. It is what the work really consumed.','Actual output achieved|Initial planned input|Initial planned output',15,'Actual Input')
term('PO','Initial planned output','This is the target result, such as 100 acceptable orders.','Actual output achieved|Initial planned input|Actual input used',16,'Planned Output')
term('AO','Actual output achieved','This is the measured result, such as 90 acceptable orders completed.','Actual input used|Initial planned output|Initial planned input',16,'Actual Output')
term('Efficiency','Planned input divided by actual input (PI / AI)','The course compares resource use with the initial plan. Keep the units comparable.','Actual output divided by planned output|Actual output divided by actual input|Actual input divided by actual output',15)
term('Effectiveness','Actual output divided by planned output (AO / PO)','It compares the achieved result with the target, rather than comparing resource use.','Planned input divided by actual input|Actual output divided by actual input|Planned output divided by actual input',16)
term('Productivity','Actual output per actual input (AO / AI)','Orders per labor hour is productivity. Compare the same units across time.','Planned input divided by actual input|Actual output divided by planned output|Actual input divided by planned output',17)
term('Cycle time','Elapsed time from a process’s start to its finish','Waiting between steps can lengthen cycle time even if individual tasks are quick.','Only the output quantity|Only the cost of purchased software|The total number of departments',20)
term('Bottleneck','A step that limits or slows the overall flow of work','A slow approval can make orders wait even if every other step is fast.','Any unused computer regardless of impact|The final customer output|A shared objective agreed by all teams',21)
term('BPM','Ongoing management of business processes','It includes running work, measuring results, and deciding how to improve it.','Only small incremental changes|Only radical process replacement|Only financial record keeping',21,'Business Process Management')
term('BPI','Incremental improvement of existing business processes','Small changes often preserve much of the current way of working.','Fundamental redesign from scratch|Only observing work without changing it|Eliminating all business processes',22,'Business Process Improvement')
term('BPR','Fundamental rethinking and radical redesign of processes','It challenges the design itself to seek large performance gains.','Small repeated tweaks to the current design|A routine to back up computer files|The same as buying any new application',23,'Business Process Re-engineering')
term('Enterprise','An organization or group of organizations with shared goals','The term can cover one company or several collaborating organizations.','Only a very large mainframe computer|Only the finance department|Any collection of unrelated customers',27)
term('EA','The overall blueprint connecting business and technology to goals','It includes business, data, applications, and technology rather than treating IT as isolated purchases.','Only the hardware installed in one room|Only the daily accounting process|Only the organization’s advertising plan',27,'Enterprise Architecture')
term('Framework','A structured way to organize and develop an architecture','It guides which views and concepts to consider; the architecture is the organization’s resulting design.','The installed hardware itself|A finished design identical for every organization|The data in one customer order',27)
term('Governance','Rules and responsibilities for making and overseeing decisions','It clarifies who decides and what standards they follow.','The speed of a processor|Only hiring new employees|A list of finished products',29)
term('SOA','An architecture built from reusable software services','A service does a defined job and can be used by multiple applications through an agreed interface.','A rule that all software must be cloud-hosted|A design that isolates every application|A single central computer with no service reuse',32,'Service-Oriented Architecture')
term('IT infrastructure','The actual technology resources and services supporting IT operations','The design specifies needs; infrastructure provides the working technology.','The business’s goals alone|Only the department reporting structure|An abstract blueprint with no implemented resources',33,'Information Technology infrastructure')
term('Platform','An environment on which applications or services run','Applications depend on the platform’s hardware/software capabilities.','A record of a customer purchase|A business goal without technical capabilities|The entire enterprise strategy',35)
term('Functional area','A specialized category of business work, often a department','Sales, HR, and accounting are functional areas; an order can cross several areas.','An individual physical computer component|A formula for measuring outputs|A complete enterprise-wide process in every case',38)
term('HR','The function responsible for people-related work such as hiring and training','HR means human resources. Its work concerns employees, not purchasing ingredients.','The function that records only supplier bills|The function that produces network hardware|The function that designs every customer invoice',39,'Human Resources')
term('Silo effect','Isolation that prioritizes department goals over shared organizational goals','A team can finish its own task while the whole customer order still fails. Shared measures and information help.','Healthy specialization with good coordination|A shared database used by all departments|A coordinated process crossing several departments',40)
term('Standardization','Agreeing on consistent procedures, formats, or definitions','Two branches can use the same form even before their systems are connected.','Connecting systems and sharing work only|Keeping all methods unrelated|Radical redesign of every business goal',42)
term('Integration','Connecting parts so they share information and work together','A sale updating both inventory and accounting connects work across functions.','Using identical forms but never sharing them|Separating each function’s records|Replacing all workers with software',43)
term('FAIS','An information system focused on one functional area','Payroll for HR illustrates functional scope; enterprise scope involves connecting multiple areas.','A system defined by company-wide integration|An operating system for a computer|An intercompany shipping contract',44,'Functional Area Information System')
term('EIS','An information system connecting enterprise functions and processes','In this course the E is Enterprise. ERP belongs within this broader category.','An isolated functional-area app by definition|Only executive dashboards in this course|Only a network connecting computers',45,'Enterprise Information System')
term('ERP','Integrated modules and shared data supporting core enterprise processes','Different departments can use the same connected transaction record.','Only production scheduling in a spreadsheet|Unconnected software for each department|Only a supplier’s public website',47,'Enterprise Resource Planning')
term('Module','A part of an ERP system supporting a particular business area','Finance and procurement modules have different jobs but can share data.','A completely unrelated system that cannot connect|A company’s long-term strategy|An individual row of customer data',47)
term('Database','An organized collection of stored data','The ERP’s shared data provides consistent records for several functions; accuracy still depends on good inputs.','Only a computer’s screen|Only a list of business goals|Only the staff working in accounting',47)
term('Data migration','Moving existing data into a new system','Incorrect conversions or missing records can affect many ERP users, so migration must be checked.','Writing a new competitive strategy|Training staff without moving records|Only buying a network cable',49)
term('Interorganizational','Across the boundaries of different organizations','A buyer and its supplier coordinating electronically are working between organizations.','Only within one department|Only within one organization|Only within a single computer',51)
term('Intraorganizational','Within one organization','Connecting sales and accounting inside one company is intraorganizational.','Across two independent companies|Only between supplier and customer companies|Only across national borders',51)
d['vocab']=v
checks=[]
def check(source,q,a,wr,why):
 checks.append(dict(id=f'304-c{len(checks)+1:02}',source=source,section=d['questions'][source-1]['section'],q=q,correct=a,distractors=wr.split('|'),teach=why,answer=a))
check(1,'A manager uses experience to apply a sales report. Which DIKW level is this?','Knowledge','Data|Information|Wisdom','Applying information using understanding is knowledge. Wisdom is the judgment used to choose a sensible action after considering the situation.')
check(3,'Which IS component is the cashier who uses the checkout system?','People','Software|Data|Processes','The cashier is a human participant. The steps they follow are the process; the app they use is software.')
check(4,'Which hardware holds active work temporarily?','RAM','Persistent storage|CPU|Network adapter','RAM is temporary working space. The CPU executes instructions; persistent storage keeps saved files.')
check(9,'A business charges a recurring fee for continued access. Which model?','Subscription','Marketplace|Franchise|Value-added reseller','Recurring access fees characterize subscriptions. A marketplace connects buyers and sellers; a franchise licenses a business approach.')
check(9,'A seller bundles equipment with installation and training. Which slide example fits?','Value-added reseller','Subscription|Advertising|Marketplace','The seller adds services to another company’s product, creating a more useful bundle.')
check(11,'In DSRP, comparing a customer’s and an employee’s views uses which pattern?','Perspectives','Distinctions|Systems|Relationships','Perspectives are viewpoints. Different people can experience the same process differently.')
check(11,'In DSRP, asking what belongs inside a system and what larger whole it belongs to uses which pattern?','Systems','Perspectives|Relationships|Distinctions','Systems thinking includes nested parts and wholes. Distinctions instead identify what something is and is not.')
check(11,'In DSRP, asking how stock shortages affect delivery uses which pattern?','Relationships','Perspectives|Distinctions|Systems','You are examining how one thing affects another: a relationship.')
check(13,'Which process model shows the proposed improved workflow?','To-be','As-is|Hardware architecture|Organizational chart','To-be describes intended future work. As-is captures how the work currently happens.')
check(13,'Which detail belongs in a process model?','Who performs an activity and which decision determines the next step','Only company revenue totals|Only hardware serial numbers|Only employee job titles without workflow','A useful process model describes work, actors, decisions, and sequence so handoffs and problems become visible.')
check(18,'A salon performs a customer’s haircut. Which core process is this work?','Production','Procurement|Accounting|Architecture','Production includes creating a service. It is not limited to making factory goods.')
check(19,'A bakery identifies a flour shortage and sends an order to a supplier. Which process?','Procurement','Fulfillment|Production|Accounting','The bakery is buying resources it needs. From the supplier’s side, supplying that order is fulfillment.')
check(19,'Which is a sensible output of the accounting process?','Checked financial records and reports','A newly baked loaf|A request to order flour|An unprocessed customer order','Accounting takes financial events as inputs, checks and organizes them, and produces records and reports.')
check(19,'Which output belongs to procurement?','Accepted supplies and purchase/payment records','Only a sales advertisement|Only a finished product made from raw materials|Only a customer’s delivery confirmation','Procurement gets resources into the organization. Production later transforms those resources.')
check(19,'Which input most directly starts fulfillment?','A customer order','A department’s internal purchase requisition|A year-end financial statement|An architectural framework','Fulfillment follows a customer’s request through preparation, delivery, and payment.')
check(19,'An employee asks the purchasing department to buy a monitor. Which document is this?','Purchase requisition','Purchase order|Sales order|Vendor invoice','The request is still internal. The organization later sends a purchase order to the selected seller.')
check(19,'The seller sends a bill. What is it called from the buyer’s perspective?','Vendor invoice','Sales order|Purchase requisition|Purchase order','The buyer receives a request to pay its vendor. The same bill is a sales invoice from the seller’s perspective.')
check(20,'A process gets faster but doubles its error rate. What should you conclude?','Evaluate speed and quality together against the goal','It is definitely better because time fell|It is definitely more effective because errors rose|Ignore quality when evaluating a process','Improvement must serve the intended outcome. Fast incorrect orders may not satisfy the goal.')
check(22,'Removing one duplicate approval from the existing workflow is usually what?','BPI','BPR|ERP II|SOA','It is a small adjustment to the current workflow rather than fundamental redesign.')
check(23,'Replacing the entire order-handling approach with a new cross-functional design is what?','BPR','BPI|FAIS|DIKW','The basic design and responsibilities are being reconsidered. That is the radical scope of re-engineering.')
check(27,'Is an EA framework the same thing as the company’s architecture?','No; the framework structures the work, while architecture is the company’s design','Yes; both mean the installed hardware|Yes; both mean only the database|No; architecture means goals only and a framework means profits','A framework supplies ways to describe and develop a design. The resulting architecture is specific to the enterprise.')
check(29,'Defining customer and order records belongs most directly to which architecture layer?','Data','Business|Application|Technology','Data architecture concerns the structure and management of data assets, including these records.')
check(29,'Defining how ordering and inventory apps interact belongs to which layer?','Application','Business|Data|Technology','Application architecture describes applications and their interactions in support of business work.')
check(29,'Defining the company’s fulfillment process and decision responsibilities belongs to which layer?','Business','Application|Data|Technology','Business architecture covers processes, organization, strategy, and governance.')
check(29,'Defining required servers, supporting software, and networks belongs to which layer?','Technology','Application|Data|Business','Technology architecture describes the capabilities needed to run applications and data services.')
check(32,'Must SOA services be hosted in the cloud?','No; reusable services can run on premises or in the cloud','Yes; any locally hosted service stops being SOA|Yes; SOA simply means any website|No; SOA forbids cloud services','SOA describes software organization around services. Hosting location is a separate choice; the slide uses a simplified cloud association.')
check(42,'Two branches use the same order form but never share records. What is present?','Standardization without integration','Integration without standardization|Both full integration and standardization|Neither, because all forms must be different','The form is consistent, but work and records are not connected between the branches.')
check(43,'A new sale automatically updates inventory and accounting. What does this illustrate?','Integration','Isolation|Decentralization by itself|Data collection without sharing','The transaction connects several business functions so each can act on shared information.')
check(47,'Does “single version of the truth” mean an ERP automatically fixes wrong data?','No; shared records still require accurate inputs and controls','Yes; shared storage guarantees all facts are correct|Yes; only separate databases can contain errors|No; ERP prevents all departments from viewing records','Shared data reduces conflicting copies, but a wrong value can still be shared widely. Data quality remains essential.')
check(49,'Moving old records into ERP is called what?','Data migration','Process differentiation|Business strategy|Functional specialization','Migration is the transfer of data into the new environment, where formats and accuracy need checking.')
check(51,'A supplier accesses a buyer’s purchasing process online. Which ERP II feature does this show?','Interorganizational support','Department isolation|Hardware centralization only|Removal of all supplier involvement','The work crosses company boundaries, extending the internal integration emphasized by ERP I.')
d['checks']=checks
sorts=[(1,'Build the DIKW order',['Data','Information','Knowledge','Wisdom'],'Facts become meaningful information, then usable understanding, then informed judgment.'),(37,'Translate strategy into a working system',['Strategic goals','Business requirements','Architectural requirements','Infrastructure choices'],'First decide the goal, then required business behavior, then the design, then concrete technology.'),(19,'Procurement: order the main steps',['Identify the need','Request approval if required','Select vendor and send purchase order','Receive and inspect resources','Pay the vendor'],'In this simplified flow, know the need before ordering and inspect delivery before paying. Contract payment timing can vary.'),(19,'Fulfillment: order this pay-after-delivery example',['Receive customer order','Record sales order','Prepare goods or service','Deliver to the customer','Bill and receive payment'],'The customer’s order starts the flow. This example bills after delivery; other businesses collect payment earlier.'),(21,'BPM: arrange one management cycle',['Design the process','Execute the process','Monitor results','Evaluate performance','Improve and repeat'],'Work is designed, used, checked, and improved. The cycle then continues.'),(13,'Build a simple order-check flow',['Receive an order','Check stock availability','Decide whether stock is sufficient','Prepare the available order','Deliver the order'],'This simplified path assumes enough stock. A full activity diagram also shows the no-stock branch.')]
d['sorts']=[dict(id=f'304-s{i+1}',source=n,section=d['questions'][n-1]['section'],q=t,items=items,teach=why) for i,(n,t,items,why) in enumerate(sorts)]
# Preserve every assigned link, separating required readings and extras.
readings=[]
def reading(s,title,url,extra=False):readings.append(dict(set=s,title=title,url=url,extra=extra))
for s,title,url,extra in [
(1,'Systems Thinking · 11:55','https://www.youtube.com/watch?v=-sfiReUu3o0',False),(1,'Derek Cabrera on DSRP · 1:21','https://www.youtube.com/watch?v=vuL6vjI3tZg',False),(1,'What is a business process? · 2:15','https://youtu.be/NXbGIilFidA',False),(1,'Purpose of a Process Model','https://www.solvexia.com/blog/process-model-purpose',False),(1,'What is a project?','https://www.projectmanagement.com/wikis/399992/what-is-a-project-',False),(1,'Order Fulfillment','https://en.wikipedia.org/wiki/Order_fulfillment',False),(1,'Purchasing Process','https://en.wikipedia.org/wiki/Purchasing_process',False),(1,'Manufacturing','https://en.wikipedia.org/wiki/Manufacturing',False),(1,'BPM · introduction and definitions','https://en.wikipedia.org/wiki/Business_process_management',False),(1,'BPI versus BPR','https://www.visual-paradigm.com/guide/business-process-reengineering/bpi-vs-bpr/',False),
(1,'DSRP','https://en.wikipedia.org/wiki/DSRP',True),(1,'Zoom In · 4:55','https://www.youtube.com/watch?v=g9k_w3TddM4',True),(1,'Zoom Out · 4:45','https://www.youtube.com/watch?v=kuDaAyUPfqo',True),(1,'Business Process · skim History and Supporting theories','https://en.wikipedia.org/wiki/Business_process',True),(1,'Activity Diagram','https://en.wikipedia.org/wiki/Activity_diagram',True),(1,'UML 2.0 Activity Diagrams · 12:23','https://www.youtube.com/watch?v=XFTAIj2N2Lc',True),(1,'Business Process Management · 3:27','https://youtu.be/WcJ8QxOZk2o',True),(1,'What is BPM? · 3:40','https://youtu.be/XtvIU0ZCwjE',True),
(2,'What is Enterprise Architecture? · 6:55','https://www.youtube.com/watch?v=9TVc32M_gIY',False),(2,'Why Enterprise Architecture? · 3:44','https://www.youtube.com/watch?v=qDI2oF1bASk&t=2s',False),(2,'EA Framework · topics, domains, and layers','https://en.wikipedia.org/wiki/Enterprise_architecture_framework',False),(2,'Centralized versus decentralized · assigned sections only','https://www.geeksforgeeks.org/system-design/comparison-centralized-decentralized-and-distributed-systems/',False),(2,'Service-Oriented Architecture','https://www.geeksforgeeks.org/software-engineering/service-oriented-architecture/',False),(2,'IT Infrastructure · definition, overview, background, components','https://en.wikipedia.org/wiki/IT_infrastructure',False),(2,'How IT and Business Process Fit Together · 3:30','https://www.youtube.com/watch?v=3iAp9me4P1c',False),(2,'Computer Platform','https://www.techopedia.com/definition/3411/platform-computing',False),(2,'What’s an enterprise anyway? · 5:39','https://www.youtube.com/watch?v=0b8JjqVfaXE',True),(2,'What is Enterprise Architecture? · 9:47','https://www.youtube.com/watch?v=V5Xisag6aN8',True),(2,'Simplest Business Architecture · 2:39','https://www.youtube.com/watch?v=gwIg_Tu5qII',True),(2,'Is Architecture Really that Complicated? · 5:36','https://www.youtube.com/watch?v=aMTOpRsgeeQ',True),(2,'Types of Software Platforms','https://www.geeksforgeeks.org/software-engineering/types-of-software-platforms/',True),
(3,'Functional versus Process View','https://bacoach.nl/2025/10/functional-vs-process-view/',False),(3,'Silo mentality · 1:39','https://www.youtube.com/watch?v=VJ51G7xNVTQ',False),(3,'Standardization in Business','https://ca.indeed.com/career-advice/career-development/standardization-in-business',False),(3,'Integrated Processes','https://ca.indeed.com/career-advice/career-development/process-integration',False),(3,'ERP · intro, expansion, characteristics, functional areas','https://en.wikipedia.org/wiki/Enterprise_resource_planning',False),(3,'Understanding Silo Mentality','https://www.investopedia.com/terms/s/silo-mentality.asp',True),(3,'What is ERP? · 1:02','https://www.youtube.com/watch?v=Ju55a1atEZw',True),(3,'What is ERP software? · 2:36','https://www.youtube.com/watch?v=6qys-562kp4',True),(3,'Silos and how to reduce them · 3:53','https://www.youtube.com/watch?v=KgSdcTpPzIk',True)]:reading(s,title,url,extra)
d['readings']=readings
d['references']=[{'title':'PMI · What is a project?','url':'https://www.pmi.org/about/what-is-a-project','questions':[14]},{'title':'Visual Paradigm · BPI versus BPR','url':'https://www.visual-paradigm.com/guide/business-process-reengineering/bpi-vs-bpr/','questions':[22,23,24,25,26]},{'title':'SolveXia · Purpose of a process model','url':'https://www.solvexia.com/blog/process-model-purpose','questions':[13]},{'title':'IBM · Service-oriented architecture','url':'https://www.ibm.com/think/topics/soa','questions':[32]},{'title':'SAP · ERP','url':'https://www.sap.com/resources/what-is-erp','questions':[47,48,49,50]},{'title':'Oracle · ERP','url':'https://www.oracle.com/erp/what-is-erp/','questions':[47,48,49,50]},{'title':'Microsoft · Dynamics 365 ERP','url':'https://www.microsoft.com/en-us/dynamics-365/solutions/erp','questions':[50]}]
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
print(len(v),'terms;',len(checks),'extra checks;',len(readings),'reading links')
d['abbreviationDistractors']={
'RAM':['Read Access Memory','Random Application Memory','Rapid Active Memory'],
'CPU':['Computer Processing Utility','Central Program Unit','Core Processing Utility'],
'IS':['Information Software','Integrated Strategy','Infrastructure System'],
'DIKW':['Data Integration Knowledge Workflow','Design Information Knowledge Work','Data Information Key Workflow'],
'DSRP':['Data Systems Resources Processes','Distinctions Strategy Relationships Productivity','Decisions Systems Requirements Perspectives'],
'UML':['Universal Management Language','Unified Modeling Logic','User Module Language'],
'PI':['Process Input','Planned Information','Productivity Index'],
'AI':['Actual Information','Architecture Input','Artificial Intelligence'],
'PO':['Process Output','Planned Organization','Productivity Outcome'],
'AO':['Architecture Output','Actual Organization','Allocated Output'],
'BPM':['Business Project Management','Business Process Modeling','Business Productivity Measurement'],
'BPI':['Business Process Integration','Business Project Improvement','Business Productivity Index'],
'BPR':['Business Process Reporting','Business Project Re-engineering','Business Performance Review'],
'EA':['Enterprise Applications','Enterprise Alignment','Electronic Architecture'],
'SOA':['System-Oriented Architecture','Service Operations Architecture','Software Organization Architecture'],
'IT infrastructure':['Integrated Technology infrastructure','Information Transmission infrastructure','Internet Technology infrastructure'],
'HR':['Hardware Resources','Human Requirements','Hiring Records'],
'FAIS':['Functional Architecture Information System','Financial Area Integration System','Functional Application Integration Software'],
'EIS':['Enterprise Integration Software','Executive Information System','Enterprise Infrastructure Service'],
'ERP':['Enterprise Resource Processing','Enterprise Requirements Planning','Enterprise Records Platform']}
# AI and EIS have other legitimate expansions elsewhere; ask within this course context.
d['cloze']=[]
for source,question,answer,wrong,why in [
(1,'Raw facts are ____; organized facts with meaning are ____.','data; information','information; data|knowledge; data|wisdom; information','Data are the starting facts. Processing or contextualizing them produces information.'),
(11,'DSRP’s ____ asks about viewpoints; ____ asks about interactions.','Perspectives; Relationships','Relationships; Perspectives|Systems; Distinctions|Distinctions; Systems','A viewpoint is a perspective. How things affect each other is a relationship.'),
(19,'An internal purchase request is a ____; the order sent to the vendor is a ____.','purchase requisition; purchase order','purchase order; purchase requisition|sales order; vendor invoice|vendor invoice; sales invoice','Internal approval happens inside the buyer. Ordering from a selected supplier goes outside the organization.'),
(15,'For efficiency, compare planned ____ with actual ____.','input; input','output; output|output; input|input; output','Efficiency in slide 20 is PI/AI: both values concern resource use.'),
(16,'For effectiveness, divide ____ output by ____ output.','actual; planned','planned; actual|actual; actual|planned; planned','The achieved result is compared with the initial output target.'),
(17,'Productivity measures actual ____ per actual ____.','output; input','input; output|output; output|input; input','The amount produced per resource unit is productivity, such as orders per hour.'),
(25,'Small changes to an existing process are ____; fundamental redesign is ____.','BPI; BPR','BPR; BPI|BPM; FAIS|ERP; BPM','Improvement preserves much of the process. Re-engineering challenges the design itself.'),
(36,'____ sets the direction; ____ designs the solution; ____ implements the technology.','Strategy; architecture; infrastructure','Infrastructure; strategy; architecture|Architecture; infrastructure; strategy|Strategy; infrastructure; architecture','Start with goals, translate them into design requirements, and then choose actual technology.'),
(43,'Consistent procedures demonstrate ____; connected processes demonstrate ____.','standardization; integration','integration; standardization|decentralization; isolation|specialization; fragmentation','The same way of working is standardization. Sharing information and coordinating work is integration.'),
(46,'____ supports a functional area; ____ connects enterprise functions.','FAIS; EIS','EIS; FAIS|ERP; FAIS|BPI; BPR','Scope and cross-functional integration distinguish these information systems.'),
(51,'Within one organization is ____; between organizations is ____.','intraorganizational; interorganizational','interorganizational; intraorganizational|decentralized; centralized|integrated; standardized','Intra means within; inter means between. ERP II extends to business partners.')]:
 d['cloze'].append(dict(id=f'304-blank{len(d["cloze"])+1}',source=source,section=d['questions'][source-1]['section'],q=question,correct=answer,distractors=wrong.split('|'),teach=why,answer=answer))
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
