import json
from pathlib import Path
p=Path(__file__).resolve().parents[3]/'dist/cis304-content.json'
d=json.loads(p.read_text())
rows=[
(1,'Raw facts are ____. Organized facts with meaning are ____.','data; information','information; data|knowledge; wisdom|wisdom; knowledge','Individual sales numbers are data. Organizing them into a sales report gives them meaning as information.'),
(1,'Understanding gained from information and experience is ____. Sound judgment in applying it reflects ____.','knowledge; wisdom','wisdom; knowledge|data; information|information; data','Knowing seasonal sales patterns is knowledge. Using that understanding to make a sensible decision adds judgment, or wisdom.'),
(3,'The five information-system components are hardware, software, data, procedures, and ____.','people','profit|strategy|buildings','An information system includes the people who use and manage it. Technology alone cannot define the entire system.'),
(4,'The ____ executes instructions; ____ holds working data for quick access.','CPU; memory','memory; CPU|storage; output|input; storage','The processor does the computing. Working memory holds information currently in use; long-term storage has a different job.'),
(5,'An operating system is ____ software; a word processor is ____ software.','system; application','application; system|hardware; network|input; output','System software manages the computing environment. Application software helps a user perform a task such as writing a document.'),
(7,'A business ____ explains how an organization will achieve its goals and compete.','strategy','database|processor|transaction','Strategy guides the organization’s choices. Decisions about processes and technology should support that direction.'),
(9,'A ____ model charges recurring fees; a ____ model offers basic service free and charges for extras.','subscription; freemium','freemium; subscription|retail; advertising|advertising; retail','A subscription involves repeated payments. Freemium combines free basic service with paid features.'),
(11,'In DSRP, D means ____ and P means ____.','distinctions; perspectives','perspectives; distinctions|relationships; systems|systems; relationships','Distinctions identify what something is and is not. Perspectives ask whose viewpoint you are using.'),
(11,'In DSRP, S means ____ and R means ____.','systems; relationships','relationships; systems|distinctions; perspectives|perspectives; distinctions','Systems involve parts and wholes. Relationships describe connections among those parts or systems.'),
(12,'A process turns ____ into ____ through related activities.','inputs; outputs','outputs; inputs|goals; departments|departments; goals','Inputs enter the work. Outputs are what it produces, such as an order becoming a delivered purchase.'),
(13,'A process ____ represents how work flows so people can understand and analyze it.','model','sponsor|platform|server','A model is a representation, such as a diagram showing steps, decisions, and handoffs. It helps reveal possible problems.'),
(14,'A project is ____; ongoing operations are ____.','temporary; continuing','continuing; temporary|standardized; decentralized|decentralized; standardized','A project ends after its particular result is delivered. Operations keep a business or service running.'),
(15,'The course efficiency formula is ____ divided by ____.','PI; AI','AI; PI|AO; PO|PO; AO','PI is planned input and AI is actual input. This compares the resources planned with those used, with output conditions kept in mind.'),
(16,'The course effectiveness formula is ____ divided by ____.','AO; PO','PO; AO|PI; AI|AI; PI','AO is actual output and PO is planned output. Their ratio compares the result achieved with the target.'),
(17,'The course productivity formula is ____ divided by ____.','AO; AI','AI; AO|PI; PO|PO; PI','Output per input means results for each unit of resource used, such as orders processed per labor hour.'),
(18,'____ obtains needed goods and services; ____ turns inputs into products or services.','procurement; production','production; procurement|fulfillment; accounting|accounting; fulfillment','Procurement acquires what is needed. Production uses inputs to create what the business provides.'),
(19,'____ delivers what the customer ordered; ____ records financial activity.','fulfillment; accounting','accounting; fulfillment|procurement; production|production; procurement','Fulfilling an order gets it to the customer. Accounting tracks the money-related records of the business.'),
(21,'____ manages processes over time; ____ improves existing processes; ____ fundamentally redesigns them.','BPM; BPI; BPR','BPR; BPM; BPI|BPI; BPR; BPM|BPM; BPR; BPI','Management is the ongoing discipline. Improvement makes an existing process better. Re-engineering rethinks it more radically.'),
(30,'____ IT concentrates control; ____ IT gives units more local control.','centralized; decentralized','decentralized; centralized|integrated; standardized|standardized; integrated','The contrast is where decisions and control sit. Local flexibility and organization-wide consistency can involve tradeoffs.'),
(32,'SOA organizes capabilities as reusable ____.','services','silos|processors|departments','A service offers a defined capability through an interface so applications or processes can use it.'),
(36,'____ sets direction; ____ provides the organizing blueprint; ____ supplies the supporting technology.','strategy; architecture; infrastructure','infrastructure; strategy; architecture|architecture; infrastructure; strategy|strategy; infrastructure; architecture','First identify what to achieve. Architecture organizes the needed capabilities; infrastructure supplies the technical foundation.'),
(40,'Departments that keep information to themselves can create the ____ effect.','silo','integration|standardization|productivity','Like separate storage silos, departments can become isolated. Their local decisions may hurt the whole process.'),
(41,'A ____ perspective follows work across departments from start to customer outcome.','business-process','functional|hardware|storage','Following the whole flow makes handoffs and shared outcomes visible instead of stopping at a department boundary.'),
(42,'____ makes practices consistent; ____ connects parts so they work together.','standardization; integration','integration; standardization|decentralization; centralization|centralization; decentralization','Using the same date format is standardization. Connecting systems so an order moves between them is integration.'),
(46,'A ____ serves a functional area; an ____ connects enterprise functions.','FAIS; EIS','EIS; FAIS|ERP; CPU|CPU; ERP','A departmental system has a narrower scope. Enterprise systems help information and work cross functional boundaries.'),
(47,'ERP stands for Enterprise ____ ____.','Resource; Planning','Relationship; Processing|Resource; Processing|Relationship; Planning','ERP coordinates major business processes and shared information. Its name refers to enterprise resources and planning.'),
(51,'ERP II extends integration beyond the organization to customers, suppliers, and other ____.','partners','processors|memory chips|operating systems','The important extension is collaboration between organizations, not merely adding more internal departments.')
]
for i,(n,q,a,w,why) in enumerate(rows,1):
 d['cloze'].append(dict(id=f'304-tapblank-{i}',kind='cloze',source=n,section=d['questions'][n-1]['section'],q=q,correct=a,answer=a,distractors=w.split('|'),teach=why,blanks=a.split('; ')))
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
